"""The verdict twin of a value the builder holds.

Generated by `scripts/generate_poll_protocols.py`; do not edit.  `check()` on a typed view hands back
that view's own twin.  This is the one a value reaches through the builder, which is where an element
pivot and the capability umbrella both land.

Flat and self-dispatched for the same measured reason the polling twins are: overloading `check()` on
the builder's own type variable put an `AssertionBuilder[Any]` on the first rung, and every chain built
from a payload typed `dict[str, Any]` then read as a string.  A rung per assertion inverts that.

A name nobody declares stays open, because `__getattr__` answers it: a dynamic assertion is resolved
from the value's own attributes and reaches this proxy too.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import datetime
    import pathlib
    from collections.abc import Callable, Hashable, Iterable, Mapping, Sized
    from pathlib import Path
    from typing import Any, Protocol, SupportsFloat, TypeVar, overload

    from .._matcher_impls import ClassInfo
    from ..matchers import Matcher
    from ..outcome import AssertionOutcome
    from ._capable_typing import _Callable, _Orderable, _PathLike
    from ._introspection import MappingLike
    from ._typing import (
        _U,
        _ArrayT_co,
        _CapableT,
        _FrameT_co,
        _Other,
        _P_co,
    )

    _KeySpecs = Hashable | list[Hashable] | set[Hashable] | frozenset[Hashable]

    _E = TypeVar("_E")
    _N = TypeVar("_N", int, float)
    _K = TypeVar("_K")
    _V = TypeVar("_V")
    _R = TypeVar("_R")
    _B_co = TypeVar("_B_co", bytes, bytearray, covariant=True)
    _U2 = TypeVar("_U2")
    _U3 = TypeVar("_U3")
    _Number = SupportsFloat

    # the rungs below restrict `self` with the annotations `assert_that()` overloads are written with
    _T = TypeVar("_T")
    _P = TypeVar("_P")

    class _CheckAnyValue(Protocol[_P_co]):
        """The verdict surface of a value reached through the builder rather than through a view."""

        @property
        def not_(self) -> _CheckAnyValue[_P_co]: ...
        def __getattr__(self, name: str) -> Callable[..., AssertionOutcome]: ...

        @overload
        def satisfies(
            self: _CheckAnyValue[str], matcher: Matcher[str] | Callable[[str], object]
        ) -> AssertionOutcome: ...
        @overload
        def satisfies(
            self: _CheckAnyValue[int] | _CheckAnyValue[float], matcher: Matcher[_N] | Callable[[_N], object]
        ) -> AssertionOutcome: ...
        @overload
        def satisfies(self, matcher: Matcher[Any] | Callable[[Any], object]) -> AssertionOutcome: ...

        @overload
        def contains(self: _CheckAnyValue[str], *items: str | Matcher[str]) -> AssertionOutcome: ...
        @overload
        def contains(self: _CheckAnyValue[dict[_K, _V]], *items: object) -> AssertionOutcome: ...
        @overload
        def contains(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            *items: _E | Matcher[_E],
        ) -> AssertionOutcome: ...
        @overload
        def contains(self: _CheckAnyValue[bytes] | _CheckAnyValue[bytearray], *items: object) -> AssertionOutcome: ...
        @overload
        def contains(
            self: _CheckAnyValue[_FrameT_co] | _CheckAnyValue[_ArrayT_co], *items: object
        ) -> AssertionOutcome: ...
        @overload
        def contains(self: _CheckAnyValue[_CapableT], *items: object) -> AssertionOutcome: ...

        def is_equal_to_ignoring_case(self: _CheckAnyValue[str], other: str) -> AssertionOutcome: ...

        def is_equal_to_ignoring_whitespace(self: _CheckAnyValue[str], other: str) -> AssertionOutcome: ...

        @overload
        def contains_ignoring_case(self: _CheckAnyValue[str], *items: str) -> AssertionOutcome: ...
        @overload
        def contains_ignoring_case(self: _CheckAnyValue[_CapableT], *items: str) -> AssertionOutcome: ...

        @overload
        def starts_with(self: _CheckAnyValue[str], prefix: str) -> AssertionOutcome: ...
        @overload
        def starts_with(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            prefix: _E,
        ) -> AssertionOutcome: ...
        @overload
        def starts_with(
            self: _CheckAnyValue[bytes] | _CheckAnyValue[bytearray], prefix: bytes | bytearray
        ) -> AssertionOutcome: ...
        @overload
        def starts_with(self: _CheckAnyValue[_CapableT], prefix: str) -> AssertionOutcome: ...

        def starts_with_ignoring_case(self: _CheckAnyValue[str], prefix: str) -> AssertionOutcome: ...

        @overload
        def ends_with(self: _CheckAnyValue[str], suffix: str) -> AssertionOutcome: ...
        @overload
        def ends_with(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            suffix: _E,
        ) -> AssertionOutcome: ...
        @overload
        def ends_with(
            self: _CheckAnyValue[bytes] | _CheckAnyValue[bytearray], suffix: bytes | bytearray
        ) -> AssertionOutcome: ...
        @overload
        def ends_with(self: _CheckAnyValue[_CapableT], suffix: str) -> AssertionOutcome: ...

        def ends_with_ignoring_case(self: _CheckAnyValue[str], suffix: str) -> AssertionOutcome: ...

        def matches(self: _CheckAnyValue[str], pattern: str) -> AssertionOutcome: ...

        def does_not_match(self: _CheckAnyValue[str], pattern: str) -> AssertionOutcome: ...

        def is_alpha(self: _CheckAnyValue[str]) -> AssertionOutcome: ...

        def is_digit(self: _CheckAnyValue[str]) -> AssertionOutcome: ...

        def is_lower(self: _CheckAnyValue[str]) -> AssertionOutcome: ...

        def is_upper(self: _CheckAnyValue[str]) -> AssertionOutcome: ...

        def is_alphanumeric(self: _CheckAnyValue[str]) -> AssertionOutcome: ...

        def is_whitespace(self: _CheckAnyValue[str]) -> AssertionOutcome: ...

        @overload
        def contains_any_of(self: _CheckAnyValue[str], *items: str) -> AssertionOutcome: ...
        @overload
        def contains_any_of(self: _CheckAnyValue[_CapableT], *items: str) -> AssertionOutcome: ...

        @overload
        def contains_none_of(self: _CheckAnyValue[str], *items: str) -> AssertionOutcome: ...
        @overload
        def contains_none_of(self: _CheckAnyValue[_CapableT], *items: str) -> AssertionOutcome: ...

        @overload
        def is_unicode(self: _CheckAnyValue[str]) -> AssertionOutcome: ...
        @overload
        def is_unicode(self: _CheckAnyValue[_CapableT]) -> AssertionOutcome: ...

        @overload
        def is_greater_than(self: _CheckAnyValue[str], other: str) -> AssertionOutcome: ...
        @overload
        def is_greater_than(
            self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float], other: _Number
        ) -> AssertionOutcome: ...
        @overload
        def is_greater_than(self: _CheckAnyValue[datetime.datetime], other: datetime.datetime) -> AssertionOutcome: ...
        @overload
        def is_greater_than(self: _CheckAnyValue[datetime.date], other: datetime.date) -> AssertionOutcome: ...
        @overload
        def is_greater_than(
            self: _CheckAnyValue[bytes] | _CheckAnyValue[bytearray], other: bytes | bytearray
        ) -> AssertionOutcome: ...
        @overload
        def is_greater_than(self: _CheckAnyValue[_T], other: Any) -> AssertionOutcome: ...
        @overload
        def is_greater_than(self: _CheckAnyValue[_Orderable], other: _Number) -> AssertionOutcome: ...

        @overload
        def is_greater_than_or_equal_to(self: _CheckAnyValue[str], other: str) -> AssertionOutcome: ...
        @overload
        def is_greater_than_or_equal_to(
            self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float], other: _Number
        ) -> AssertionOutcome: ...
        @overload
        def is_greater_than_or_equal_to(
            self: _CheckAnyValue[datetime.datetime], other: datetime.datetime
        ) -> AssertionOutcome: ...
        @overload
        def is_greater_than_or_equal_to(
            self: _CheckAnyValue[datetime.date], other: datetime.date
        ) -> AssertionOutcome: ...
        @overload
        def is_greater_than_or_equal_to(
            self: _CheckAnyValue[bytes] | _CheckAnyValue[bytearray], other: bytes | bytearray
        ) -> AssertionOutcome: ...
        @overload
        def is_greater_than_or_equal_to(self: _CheckAnyValue[_T], other: Any) -> AssertionOutcome: ...
        @overload
        def is_greater_than_or_equal_to(self: _CheckAnyValue[_Orderable], other: _Number) -> AssertionOutcome: ...

        @overload
        def is_less_than(self: _CheckAnyValue[str], other: str) -> AssertionOutcome: ...
        @overload
        def is_less_than(
            self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float], other: _Number
        ) -> AssertionOutcome: ...
        @overload
        def is_less_than(self: _CheckAnyValue[datetime.datetime], other: datetime.datetime) -> AssertionOutcome: ...
        @overload
        def is_less_than(self: _CheckAnyValue[datetime.date], other: datetime.date) -> AssertionOutcome: ...
        @overload
        def is_less_than(
            self: _CheckAnyValue[bytes] | _CheckAnyValue[bytearray], other: bytes | bytearray
        ) -> AssertionOutcome: ...
        @overload
        def is_less_than(self: _CheckAnyValue[_T], other: Any) -> AssertionOutcome: ...
        @overload
        def is_less_than(self: _CheckAnyValue[_Orderable], other: _Number) -> AssertionOutcome: ...

        @overload
        def is_less_than_or_equal_to(self: _CheckAnyValue[str], other: str) -> AssertionOutcome: ...
        @overload
        def is_less_than_or_equal_to(
            self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float], other: _Number
        ) -> AssertionOutcome: ...
        @overload
        def is_less_than_or_equal_to(
            self: _CheckAnyValue[datetime.datetime], other: datetime.datetime
        ) -> AssertionOutcome: ...
        @overload
        def is_less_than_or_equal_to(self: _CheckAnyValue[datetime.date], other: datetime.date) -> AssertionOutcome: ...
        @overload
        def is_less_than_or_equal_to(
            self: _CheckAnyValue[bytes] | _CheckAnyValue[bytearray], other: bytes | bytearray
        ) -> AssertionOutcome: ...
        @overload
        def is_less_than_or_equal_to(self: _CheckAnyValue[_T], other: Any) -> AssertionOutcome: ...
        @overload
        def is_less_than_or_equal_to(self: _CheckAnyValue[_Orderable], other: _Number) -> AssertionOutcome: ...

        @overload
        def does_not_contain(self: _CheckAnyValue[str], *items: str | Matcher[str]) -> AssertionOutcome: ...
        @overload
        def does_not_contain(self: _CheckAnyValue[dict[_K, _V]], *items: object) -> AssertionOutcome: ...
        @overload
        def does_not_contain(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            *items: _E | Matcher[_E],
        ) -> AssertionOutcome: ...
        @overload
        def does_not_contain(self: _CheckAnyValue[_CapableT], *items: str | Matcher[str]) -> AssertionOutcome: ...

        @overload
        def contains_only(self: _CheckAnyValue[str], *items: str | Matcher[str]) -> AssertionOutcome: ...
        @overload
        def contains_only(self: _CheckAnyValue[dict[_K, _V]], *keys: object) -> AssertionOutcome: ...
        @overload
        def contains_only(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            *items: _E | Matcher[_E],
        ) -> AssertionOutcome: ...
        @overload
        def contains_only(
            self: _CheckAnyValue[_FrameT_co] | _CheckAnyValue[_ArrayT_co], *items: object
        ) -> AssertionOutcome: ...
        @overload
        def contains_only(self: _CheckAnyValue[_CapableT], *items: object) -> AssertionOutcome: ...

        @overload
        def contains_sequence(self: _CheckAnyValue[str], *items: str | Matcher[str]) -> AssertionOutcome: ...
        @overload
        def contains_sequence(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            *items: _E | Matcher[_E],
        ) -> AssertionOutcome: ...
        @overload
        def contains_sequence(self: _CheckAnyValue[_CapableT], *items: str | Matcher[str]) -> AssertionOutcome: ...

        @overload
        def contains_exactly(self: _CheckAnyValue[str], *items: str | Matcher[str]) -> AssertionOutcome: ...
        @overload
        def contains_exactly(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            *items: _E | Matcher[_E],
        ) -> AssertionOutcome: ...
        @overload
        def contains_exactly(self: _CheckAnyValue[_CapableT], *items: str | Matcher[str]) -> AssertionOutcome: ...

        @overload
        def contains_exactly_in_any_order(
            self: _CheckAnyValue[str], *items: str | Matcher[str]
        ) -> AssertionOutcome: ...
        @overload
        def contains_exactly_in_any_order(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            *items: _E | Matcher[_E],
        ) -> AssertionOutcome: ...
        @overload
        def contains_exactly_in_any_order(
            self: _CheckAnyValue[_CapableT], *items: str | Matcher[str]
        ) -> AssertionOutcome: ...

        @overload
        def is_sorted(
            self: _CheckAnyValue[str],
            key: Callable[[str], object] = ...,
            reverse: bool = ...,
            *,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...
        @overload
        def is_sorted(
            self: _CheckAnyValue[dict[_K, _V]],
            key: Callable[[_K], object] = ...,
            reverse: bool = ...,
            *,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...
        @overload
        def is_sorted(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            key: Callable[[_E], object] = ...,
            reverse: bool = ...,
            *,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...
        @overload
        def is_sorted(
            self: _CheckAnyValue[bytes] | _CheckAnyValue[bytearray],
            key: Callable[[int], object] = ...,
            reverse: bool = ...,
            *,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...
        @overload
        def is_sorted(
            self: _CheckAnyValue[_CapableT],
            key: Callable[[str], object] = ...,
            reverse: bool = ...,
            *,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...

        @overload
        def each(
            self: _CheckAnyValue[str], matcher: Matcher[str] | Callable[[str], object], *, allow_empty: bool = ...
        ) -> AssertionOutcome: ...
        @overload
        def each(
            self: _CheckAnyValue[dict[_K, _V]],
            matcher: Matcher[_K] | Callable[[_K], object],
            *,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...
        @overload
        def each(
            self: _CheckAnyValue[dict[_K, _V]]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]]
            | _CheckAnyValue[_FrameT_co]
            | _CheckAnyValue[_ArrayT_co],
            matcher: Matcher[Any] | Callable[[Any], object],
            *,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...
        @overload
        def each(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            matcher: Matcher[_E] | Callable[[_E], object],
            *,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...
        @overload
        def each(
            self: _CheckAnyValue[_CapableT], matcher: Matcher[Any] | Callable[[Any], object], *, allow_empty: bool = ...
        ) -> AssertionOutcome: ...

        @overload
        def all_satisfy(
            self: _CheckAnyValue[str], matcher: Matcher[str] | Callable[[str], object], *, allow_empty: bool = ...
        ) -> AssertionOutcome: ...
        @overload
        def all_satisfy(
            self: _CheckAnyValue[dict[_K, _V]],
            matcher: Matcher[_K] | Callable[[_K], object],
            *,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...
        @overload
        def all_satisfy(
            self: _CheckAnyValue[dict[_K, _V]]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]]
            | _CheckAnyValue[_FrameT_co]
            | _CheckAnyValue[_ArrayT_co],
            matcher: Matcher[Any] | Callable[[Any], object],
            *,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...
        @overload
        def all_satisfy(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            matcher: Matcher[_E] | Callable[[_E], object],
            *,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...
        @overload
        def all_satisfy(
            self: _CheckAnyValue[_CapableT], matcher: Matcher[Any] | Callable[[Any], object], *, allow_empty: bool = ...
        ) -> AssertionOutcome: ...

        @overload
        def any_satisfy(
            self: _CheckAnyValue[str], matcher: Matcher[str] | Callable[[str], object]
        ) -> AssertionOutcome: ...
        @overload
        def any_satisfy(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            matcher: Matcher[_E] | Callable[[_E], object],
        ) -> AssertionOutcome: ...
        @overload
        def any_satisfy(
            self: _CheckAnyValue[_CapableT], matcher: Matcher[str] | Callable[[str], object]
        ) -> AssertionOutcome: ...

        @overload
        def none_satisfy(
            self: _CheckAnyValue[str], matcher: Matcher[str] | Callable[[str], object]
        ) -> AssertionOutcome: ...
        @overload
        def none_satisfy(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            matcher: Matcher[_E] | Callable[[_E], object],
        ) -> AssertionOutcome: ...
        @overload
        def none_satisfy(
            self: _CheckAnyValue[_CapableT], matcher: Matcher[str] | Callable[[str], object]
        ) -> AssertionOutcome: ...

        @overload
        def satisfies_exactly(
            self: _CheckAnyValue[str], *matchers: Matcher[str] | Callable[[str], object]
        ) -> AssertionOutcome: ...
        @overload
        def satisfies_exactly(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            *matchers: Matcher[_E] | Callable[[_E], object],
        ) -> AssertionOutcome: ...
        @overload
        def satisfies_exactly(
            self: _CheckAnyValue[_CapableT], *matchers: Matcher[str] | Callable[[str], object]
        ) -> AssertionOutcome: ...

        @overload
        def satisfies_exactly_in_any_order(
            self: _CheckAnyValue[str], *matchers: Matcher[str] | Callable[[str], object]
        ) -> AssertionOutcome: ...
        @overload
        def satisfies_exactly_in_any_order(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            *matchers: Matcher[_E] | Callable[[_E], object],
        ) -> AssertionOutcome: ...
        @overload
        def satisfies_exactly_in_any_order(
            self: _CheckAnyValue[_CapableT], *matchers: Matcher[str] | Callable[[str], object]
        ) -> AssertionOutcome: ...

        @overload
        def zip_satisfies(
            self: _CheckAnyValue[str],
            other: Iterable[_Other],
            predicate: Callable[[str, _Other], object],
            *,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...
        @overload
        def zip_satisfies(
            self: _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            other: Iterable[_Other],
            predicate: Callable[[_E, _Other], object],
            *,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...
        @overload
        def zip_satisfies(
            self: _CheckAnyValue[_CapableT],
            other: Iterable[_Other],
            predicate: Callable[[str, _Other], object],
            *,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...

        def extracting_group(self: _CheckAnyValue[str], pattern: str, group: int | str = ...) -> AssertionOutcome: ...

        def matches_with_groups(self: _CheckAnyValue[str], pattern: str) -> AssertionOutcome: ...

        @overload
        def is_subset_of(
            self: _CheckAnyValue[str]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]]
            | _CheckAnyValue[bytes]
            | _CheckAnyValue[bytearray]
            | _CheckAnyValue[_FrameT_co]
            | _CheckAnyValue[_ArrayT_co],
            *supersets: object,
            allow_empty: bool = ...,
        ) -> AssertionOutcome: ...
        @overload
        def is_subset_of(
            self: _CheckAnyValue[dict[_K, _V]], *supersets: Mapping[Any, Any] | MappingLike, allow_empty: bool = ...
        ) -> AssertionOutcome: ...
        @overload
        def is_subset_of(
            self: _CheckAnyValue[_CapableT], *supersets: object, allow_empty: bool = ...
        ) -> AssertionOutcome: ...

        @overload
        def contains_duplicates(
            self: _CheckAnyValue[str]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
        ) -> AssertionOutcome: ...
        @overload
        def contains_duplicates(self: _CheckAnyValue[_CapableT]) -> AssertionOutcome: ...

        @overload
        def does_not_contain_duplicates(
            self: _CheckAnyValue[str]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
        ) -> AssertionOutcome: ...
        @overload
        def does_not_contain_duplicates(self: _CheckAnyValue[_CapableT]) -> AssertionOutcome: ...

        @overload
        def contains_only_once(
            self: _CheckAnyValue[str]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            *items: object,
        ) -> AssertionOutcome: ...
        @overload
        def contains_only_once(self: _CheckAnyValue[_CapableT], *items: object) -> AssertionOutcome: ...

        @overload
        def contains_in_order(
            self: _CheckAnyValue[str]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            *items: _E | Matcher[_E],
        ) -> AssertionOutcome: ...
        @overload
        def contains_in_order(self: _CheckAnyValue[_CapableT], *items: _E | Matcher[_E]) -> AssertionOutcome: ...

        @overload
        def has_same_size_as(
            self: _CheckAnyValue[str]
            | _CheckAnyValue[dict[_K, _V]]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]]
            | _CheckAnyValue[bytes]
            | _CheckAnyValue[bytearray]
            | _CheckAnyValue[_FrameT_co]
            | _CheckAnyValue[_ArrayT_co],
            other: Sized,
        ) -> AssertionOutcome: ...
        @overload
        def has_same_size_as(self: _CheckAnyValue[_CapableT], other: Sized) -> AssertionOutcome: ...

        @overload
        def has_size_greater_than(
            self: _CheckAnyValue[str]
            | _CheckAnyValue[dict[_K, _V]]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]]
            | _CheckAnyValue[bytes]
            | _CheckAnyValue[bytearray]
            | _CheckAnyValue[_FrameT_co]
            | _CheckAnyValue[_ArrayT_co],
            size: int,
        ) -> AssertionOutcome: ...
        @overload
        def has_size_greater_than(self: _CheckAnyValue[_CapableT], size: int) -> AssertionOutcome: ...

        @overload
        def has_size_less_than(
            self: _CheckAnyValue[str]
            | _CheckAnyValue[dict[_K, _V]]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]]
            | _CheckAnyValue[bytes]
            | _CheckAnyValue[bytearray]
            | _CheckAnyValue[_FrameT_co]
            | _CheckAnyValue[_ArrayT_co],
            size: int,
        ) -> AssertionOutcome: ...
        @overload
        def has_size_less_than(self: _CheckAnyValue[_CapableT], size: int) -> AssertionOutcome: ...

        @overload
        def has_size_between(
            self: _CheckAnyValue[str]
            | _CheckAnyValue[dict[_K, _V]]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]]
            | _CheckAnyValue[bytes]
            | _CheckAnyValue[bytearray]
            | _CheckAnyValue[_FrameT_co]
            | _CheckAnyValue[_ArrayT_co],
            low: int,
            high: int,
        ) -> AssertionOutcome: ...
        @overload
        def has_size_between(self: _CheckAnyValue[_CapableT], low: int, high: int) -> AssertionOutcome: ...

        @overload
        def is_empty(
            self: _CheckAnyValue[str]
            | _CheckAnyValue[dict[_K, _V]]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]]
            | _CheckAnyValue[bytes]
            | _CheckAnyValue[bytearray]
            | _CheckAnyValue[_FrameT_co]
            | _CheckAnyValue[_ArrayT_co],
        ) -> AssertionOutcome: ...
        @overload
        def is_empty(self: _CheckAnyValue[_CapableT]) -> AssertionOutcome: ...

        @overload
        def is_not_empty(
            self: _CheckAnyValue[str]
            | _CheckAnyValue[dict[_K, _V]]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]]
            | _CheckAnyValue[bytes]
            | _CheckAnyValue[bytearray]
            | _CheckAnyValue[_FrameT_co]
            | _CheckAnyValue[_ArrayT_co],
        ) -> AssertionOutcome: ...
        @overload
        def is_not_empty(self: _CheckAnyValue[_CapableT]) -> AssertionOutcome: ...

        @overload
        def exists(self: _CheckAnyValue[str] | _CheckAnyValue[pathlib.Path]) -> AssertionOutcome: ...
        @overload
        def exists(self: _CheckAnyValue[_PathLike]) -> AssertionOutcome: ...

        @overload
        def does_not_exist(self: _CheckAnyValue[str] | _CheckAnyValue[pathlib.Path]) -> AssertionOutcome: ...
        @overload
        def does_not_exist(self: _CheckAnyValue[_PathLike]) -> AssertionOutcome: ...

        @overload
        def is_file(self: _CheckAnyValue[str] | _CheckAnyValue[pathlib.Path]) -> AssertionOutcome: ...
        @overload
        def is_file(self: _CheckAnyValue[_PathLike]) -> AssertionOutcome: ...

        @overload
        def is_directory(self: _CheckAnyValue[str] | _CheckAnyValue[pathlib.Path]) -> AssertionOutcome: ...
        @overload
        def is_directory(self: _CheckAnyValue[_PathLike]) -> AssertionOutcome: ...

        @overload
        def is_named(self: _CheckAnyValue[str] | _CheckAnyValue[pathlib.Path], filename: str) -> AssertionOutcome: ...
        @overload
        def is_named(self: _CheckAnyValue[_PathLike], filename: str) -> AssertionOutcome: ...

        @overload
        def is_child_of(
            self: _CheckAnyValue[str] | _CheckAnyValue[pathlib.Path], parent: object
        ) -> AssertionOutcome: ...
        @overload
        def is_child_of(self: _CheckAnyValue[_PathLike], parent: object) -> AssertionOutcome: ...

        @overload
        def is_readable(self: _CheckAnyValue[str] | _CheckAnyValue[pathlib.Path]) -> AssertionOutcome: ...
        @overload
        def is_readable(self: _CheckAnyValue[_PathLike]) -> AssertionOutcome: ...

        @overload
        def is_writable(self: _CheckAnyValue[str] | _CheckAnyValue[pathlib.Path]) -> AssertionOutcome: ...
        @overload
        def is_writable(self: _CheckAnyValue[_PathLike]) -> AssertionOutcome: ...

        @overload
        def is_executable(self: _CheckAnyValue[str] | _CheckAnyValue[pathlib.Path]) -> AssertionOutcome: ...
        @overload
        def is_executable(self: _CheckAnyValue[_PathLike]) -> AssertionOutcome: ...

        @overload
        def is_positive(
            self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float],
        ) -> AssertionOutcome: ...
        @overload
        def is_positive(self: _CheckAnyValue[_Orderable]) -> AssertionOutcome: ...

        @overload
        def is_negative(
            self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float],
        ) -> AssertionOutcome: ...
        @overload
        def is_negative(self: _CheckAnyValue[_Orderable]) -> AssertionOutcome: ...

        @overload
        def is_nan(self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float]) -> AssertionOutcome: ...
        @overload
        def is_nan(self: _CheckAnyValue[_CapableT]) -> AssertionOutcome: ...

        @overload
        def is_not_nan(
            self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float],
        ) -> AssertionOutcome: ...
        @overload
        def is_not_nan(self: _CheckAnyValue[_CapableT]) -> AssertionOutcome: ...

        @overload
        def is_inf(self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float]) -> AssertionOutcome: ...
        @overload
        def is_inf(self: _CheckAnyValue[_CapableT]) -> AssertionOutcome: ...

        @overload
        def is_not_inf(
            self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float],
        ) -> AssertionOutcome: ...
        @overload
        def is_not_inf(self: _CheckAnyValue[_CapableT]) -> AssertionOutcome: ...

        @overload
        def is_close_to(
            self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float], other: _Number, tolerance: _Number
        ) -> AssertionOutcome: ...
        @overload
        def is_close_to(
            self: _CheckAnyValue[datetime.datetime], other: datetime.datetime, tolerance: datetime.timedelta
        ) -> AssertionOutcome: ...
        @overload
        def is_close_to(self: _CheckAnyValue[_CapableT], other: _Number, tolerance: _Number) -> AssertionOutcome: ...

        @overload
        def is_not_close_to(
            self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float], other: _Number, tolerance: _Number
        ) -> AssertionOutcome: ...
        @overload
        def is_not_close_to(
            self: _CheckAnyValue[datetime.datetime], other: datetime.datetime, tolerance: datetime.timedelta
        ) -> AssertionOutcome: ...
        @overload
        def is_not_close_to(
            self: _CheckAnyValue[_CapableT], other: _Number, tolerance: _Number
        ) -> AssertionOutcome: ...

        @overload
        def is_not_between(
            self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float], low: _Number, high: _Number
        ) -> AssertionOutcome: ...
        @overload
        def is_not_between(self: _CheckAnyValue[_T], low: Any, high: Any) -> AssertionOutcome: ...
        @overload
        def is_not_between(self: _CheckAnyValue[_CapableT], low: _Number, high: _Number) -> AssertionOutcome: ...

        @overload
        def is_between(
            self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float], low: _Number, high: _Number
        ) -> AssertionOutcome: ...
        @overload
        def is_between(
            self: _CheckAnyValue[datetime.datetime], low: datetime.datetime, high: datetime.datetime
        ) -> AssertionOutcome: ...
        @overload
        def is_between(
            self: _CheckAnyValue[datetime.date], low: datetime.date, high: datetime.date
        ) -> AssertionOutcome: ...
        @overload
        def is_between(self: _CheckAnyValue[_T], low: Any, high: Any) -> AssertionOutcome: ...
        @overload
        def is_between(self: _CheckAnyValue[_CapableT], low: _Number, high: _Number) -> AssertionOutcome: ...

        @overload
        def is_zero(
            self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float] | _CheckAnyValue[complex],
        ) -> AssertionOutcome: ...
        @overload
        def is_zero(self: _CheckAnyValue[_CapableT]) -> AssertionOutcome: ...

        @overload
        def is_not_zero(
            self: _CheckAnyValue[bool] | _CheckAnyValue[int] | _CheckAnyValue[float] | _CheckAnyValue[complex],
        ) -> AssertionOutcome: ...
        @overload
        def is_not_zero(self: _CheckAnyValue[_CapableT]) -> AssertionOutcome: ...

        @overload
        def is_even(self: _CheckAnyValue[int] | _CheckAnyValue[float]) -> AssertionOutcome: ...
        @overload
        def is_even(self: _CheckAnyValue[int]) -> AssertionOutcome: ...

        @overload
        def is_odd(self: _CheckAnyValue[int] | _CheckAnyValue[float]) -> AssertionOutcome: ...
        @overload
        def is_odd(self: _CheckAnyValue[int]) -> AssertionOutcome: ...

        @overload
        def is_divisible_by(self: _CheckAnyValue[int] | _CheckAnyValue[float], divisor: int) -> AssertionOutcome: ...
        @overload
        def is_divisible_by(self: _CheckAnyValue[int], divisor: int) -> AssertionOutcome: ...

        @overload
        def contains_key(self: _CheckAnyValue[dict[_K, _V]], *keys: _K | Matcher[_K]) -> AssertionOutcome: ...
        @overload
        def contains_key(self: _CheckAnyValue[_CapableT], *keys: _K | Matcher[_K]) -> AssertionOutcome: ...

        @overload
        def does_not_contain_key(self: _CheckAnyValue[dict[_K, _V]], *keys: _K | Matcher[_K]) -> AssertionOutcome: ...
        @overload
        def does_not_contain_key(self: _CheckAnyValue[_CapableT], *keys: _K | Matcher[_K]) -> AssertionOutcome: ...

        @overload
        def contains_value(self: _CheckAnyValue[dict[_K, _V]], *values: _V | Matcher[_V]) -> AssertionOutcome: ...
        @overload
        def contains_value(self: _CheckAnyValue[_CapableT], *values: _V | Matcher[_V]) -> AssertionOutcome: ...

        @overload
        def does_not_contain_value(
            self: _CheckAnyValue[dict[_K, _V]], *values: _V | Matcher[_V]
        ) -> AssertionOutcome: ...
        @overload
        def does_not_contain_value(self: _CheckAnyValue[_CapableT], *values: _V | Matcher[_V]) -> AssertionOutcome: ...

        @overload
        def contains_entry(self: _CheckAnyValue[dict[_K, _V]], *args: object, **kwargs: object) -> AssertionOutcome: ...
        @overload
        def contains_entry(self: _CheckAnyValue[_CapableT], *args: object, **kwargs: object) -> AssertionOutcome: ...

        @overload
        def does_not_contain_entry(
            self: _CheckAnyValue[dict[_K, _V]], *args: object, **kwargs: object
        ) -> AssertionOutcome: ...
        @overload
        def does_not_contain_entry(
            self: _CheckAnyValue[_CapableT], *args: object, **kwargs: object
        ) -> AssertionOutcome: ...

        @overload
        def matches_structure(self: _CheckAnyValue[dict[_K, _V]], spec: dict[Any, Any]) -> AssertionOutcome: ...
        @overload
        def matches_structure(self: _CheckAnyValue[_T], spec: dict[Any, Any]) -> AssertionOutcome: ...
        @overload
        def matches_structure(self: _CheckAnyValue[_CapableT], spec: dict[Any, Any]) -> AssertionOutcome: ...

        @overload
        def has_json_path(
            self: _CheckAnyValue[dict[_K, _V]]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            path: str,
        ) -> AssertionOutcome: ...
        @overload
        def has_json_path(self: _CheckAnyValue[_CapableT], path: str) -> AssertionOutcome: ...

        @overload
        def does_not_have_json_path(
            self: _CheckAnyValue[dict[_K, _V]]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            path: str,
        ) -> AssertionOutcome: ...
        @overload
        def does_not_have_json_path(self: _CheckAnyValue[_CapableT], path: str) -> AssertionOutcome: ...

        @overload
        def matches_json_schema(
            self: _CheckAnyValue[dict[_K, _V]]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            schema: dict[str, Any],
        ) -> AssertionOutcome: ...
        @overload
        def matches_json_schema(self: _CheckAnyValue[_CapableT], schema: dict[str, Any]) -> AssertionOutcome: ...

        @overload
        def matches_json_schema_from_file(
            self: _CheckAnyValue[dict[_K, _V]]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            path: str | Path,
        ) -> AssertionOutcome: ...
        @overload
        def matches_json_schema_from_file(self: _CheckAnyValue[_CapableT], path: str | Path) -> AssertionOutcome: ...

        @overload
        def conforms_to_openapi(
            self: _CheckAnyValue[dict[_K, _V]]
            | _CheckAnyValue[list[_E]]
            | _CheckAnyValue[tuple[_E, ...]]
            | _CheckAnyValue[set[_E]]
            | _CheckAnyValue[frozenset[_E]],
            spec: dict[str, Any],
            path: str,
            method: str,
            *,
            status: str | int | None = ...,
            content_type: str = ...,
        ) -> AssertionOutcome: ...
        @overload
        def conforms_to_openapi(
            self: _CheckAnyValue[_CapableT],
            spec: dict[str, Any],
            path: str,
            method: str,
            *,
            status: str | int | None = ...,
            content_type: str = ...,
        ) -> AssertionOutcome: ...

        def is_before(self: _CheckAnyValue[datetime.datetime], other: datetime.datetime) -> AssertionOutcome: ...

        def is_after(self: _CheckAnyValue[datetime.datetime], other: datetime.datetime) -> AssertionOutcome: ...

        def is_before_or_equal_to(
            self: _CheckAnyValue[datetime.datetime], other: datetime.datetime
        ) -> AssertionOutcome: ...

        def is_after_or_equal_to(
            self: _CheckAnyValue[datetime.datetime], other: datetime.datetime
        ) -> AssertionOutcome: ...

        def is_equal_to_ignoring_milliseconds(
            self: _CheckAnyValue[datetime.datetime], other: datetime.datetime
        ) -> AssertionOutcome: ...

        def is_equal_to_ignoring_seconds(
            self: _CheckAnyValue[datetime.datetime], other: datetime.datetime
        ) -> AssertionOutcome: ...

        def is_equal_to_ignoring_time(
            self: _CheckAnyValue[datetime.datetime], other: datetime.datetime
        ) -> AssertionOutcome: ...

        @overload
        def is_valid_utf8(self: _CheckAnyValue[bytes] | _CheckAnyValue[bytearray]) -> AssertionOutcome: ...
        @overload
        def is_valid_utf8(self: _CheckAnyValue[bytes | bytearray]) -> AssertionOutcome: ...

        @overload
        def is_valid_encoding(
            self: _CheckAnyValue[bytes] | _CheckAnyValue[bytearray], encoding: str
        ) -> AssertionOutcome: ...
        @overload
        def is_valid_encoding(self: _CheckAnyValue[bytes | bytearray], encoding: str) -> AssertionOutcome: ...

        @overload
        def starts_with_bytes(
            self: _CheckAnyValue[bytes] | _CheckAnyValue[bytearray], prefix: bytes | bytearray
        ) -> AssertionOutcome: ...
        @overload
        def starts_with_bytes(
            self: _CheckAnyValue[bytes | bytearray], prefix: bytes | bytearray
        ) -> AssertionOutcome: ...

        @overload
        def contains_bytes(
            self: _CheckAnyValue[bytes] | _CheckAnyValue[bytearray], sub: bytes | bytearray
        ) -> AssertionOutcome: ...
        @overload
        def contains_bytes(self: _CheckAnyValue[bytes | bytearray], sub: bytes | bytearray) -> AssertionOutcome: ...

        @overload
        def has_byte_at(
            self: _CheckAnyValue[bytes] | _CheckAnyValue[bytearray], index: int, expected: int
        ) -> AssertionOutcome: ...
        @overload
        def has_byte_at(self: _CheckAnyValue[bytes | bytearray], index: int, expected: int) -> AssertionOutcome: ...

        @overload
        def is_hex_equal_to(
            self: _CheckAnyValue[bytes] | _CheckAnyValue[bytearray], expected_hex: str
        ) -> AssertionOutcome: ...
        @overload
        def is_hex_equal_to(self: _CheckAnyValue[bytes | bytearray], expected_hex: str) -> AssertionOutcome: ...

        @overload
        def is_frame_equal(self: _CheckAnyValue[_FrameT_co], expected: object, **options: Any) -> AssertionOutcome: ...
        @overload
        def is_frame_equal(self: _CheckAnyValue[_CapableT], expected: object, **options: Any) -> AssertionOutcome: ...

        @overload
        def is_array_equal(
            self: _CheckAnyValue[_FrameT_co] | _CheckAnyValue[_ArrayT_co], expected: object, **options: Any
        ) -> AssertionOutcome: ...
        @overload
        def is_array_equal(self: _CheckAnyValue[_CapableT], expected: object, **options: Any) -> AssertionOutcome: ...

        @overload
        def is_array_close_to(
            self: _CheckAnyValue[_FrameT_co] | _CheckAnyValue[_ArrayT_co],
            expected: object,
            *,
            rtol: float = ...,
            atol: float = ...,
            equal_nan: bool = ...,
            **options: Any,
        ) -> AssertionOutcome: ...
        @overload
        def is_array_close_to(
            self: _CheckAnyValue[_CapableT],
            expected: object,
            *,
            rtol: float = ...,
            atol: float = ...,
            equal_nan: bool = ...,
            **options: Any,
        ) -> AssertionOutcome: ...

        @overload
        def when_called_with(
            self: _CheckAnyValue[Callable[..., _P]], *some_args: object, **some_kwargs: object
        ) -> AssertionOutcome: ...
        @overload
        def when_called_with(
            self: _CheckAnyValue[_Callable], *some_args: object, **some_kwargs: object
        ) -> AssertionOutcome: ...

        @overload
        def is_not_none(self: _CheckAnyValue[str | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[bool | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[int | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[float | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[complex | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[dict[_K, _V] | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[list[_E] | tuple[_E, ...] | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[set[_E] | frozenset[_E] | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[datetime.datetime | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[datetime.date | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[Path | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[bytes | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[bytearray | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[Callable[..., object] | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[_U | None]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self: _CheckAnyValue[_T]) -> AssertionOutcome: ...
        @overload
        def is_not_none(self) -> AssertionOutcome: ...

        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: type[str]) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: type[bool]) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: type[int]) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: type[float]) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: type[complex]) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: type[dict[_K, _V]]) -> AssertionOutcome: ...
        @overload
        def is_instance_of(
            self: _CheckAnyValue[_T], some_class: type[list[_E] | tuple[_E, ...]]
        ) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: type[set[_E] | frozenset[_E]]) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: type[datetime.datetime]) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: type[datetime.date]) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: type[Path]) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: type[bytes]) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: type[bytearray]) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: tuple[type[_U], type[_U2]]) -> AssertionOutcome: ...
        @overload
        def is_instance_of(
            self: _CheckAnyValue[_T], some_class: tuple[type[_U], type[_U2], type[_U3]]
        ) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: type[_U]) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self: _CheckAnyValue[_T], some_class: ClassInfo) -> AssertionOutcome: ...
        @overload
        def is_instance_of(self, some_class: ClassInfo) -> AssertionOutcome: ...

        @overload
        def is_instance_of_any(self: _CheckAnyValue[_T], first: type[_U], second: type[_U2], /) -> AssertionOutcome: ...
        @overload
        def is_instance_of_any(
            self: _CheckAnyValue[_T], first: type[_U], second: type[_U2], third: type[_U3], /
        ) -> AssertionOutcome: ...
        @overload
        def is_instance_of_any(self: _CheckAnyValue[_T], *some_classes: ClassInfo) -> AssertionOutcome: ...
        @overload
        def is_instance_of_any(self, *some_classes: ClassInfo) -> AssertionOutcome: ...

        def is_equal_to(
            self,
            other: object,
            *,
            ignore: _KeySpecs | None = ...,
            include: _KeySpecs | None = ...,
            tolerance: float | None = ...,
            comparators: dict[Any, Callable[[Any, Any], Any]] | None = ...,
            ignore_null: bool = ...,
            strict_types: bool = ...,
        ) -> AssertionOutcome: ...

        def is_not_equal_to(self, other: object) -> AssertionOutcome: ...

        def is_same_as(self, other: object) -> AssertionOutcome: ...

        def is_not_same_as(self, other: object) -> AssertionOutcome: ...

        def is_true(self) -> AssertionOutcome: ...

        def is_false(self) -> AssertionOutcome: ...

        def is_none(self) -> AssertionOutcome: ...

        def is_type_of(self, some_type: type) -> AssertionOutcome: ...

        def is_subclass_of(self, some_class: type) -> AssertionOutcome: ...

        def is_length(self, length: int) -> AssertionOutcome: ...

        def is_length_between(self, low: int, high: int) -> AssertionOutcome: ...

        def is_callable(self) -> AssertionOutcome: ...

        def is_not_callable(self) -> AssertionOutcome: ...

        def is_iterable(self) -> AssertionOutcome: ...

        def is_not_iterable(self) -> AssertionOutcome: ...

        def all_fields_satisfy(
            self, matcher: Matcher[Any] | Callable[[Any], object], *, allow_empty: bool = ...
        ) -> AssertionOutcome: ...

        def has_no_none_fields(self, *, allow_empty: bool = ...) -> AssertionOutcome: ...

        def is_in(self, *items: object) -> AssertionOutcome: ...

        def is_not_in(self, *items: object) -> AssertionOutcome: ...

        def snapshot(
            self,
            id: str | None = ...,
            path: str = ...,
            *,
            ignore: _KeySpecs | None = ...,
            include: _KeySpecs | None = ...,
            tolerance: float | None = ...,
            comparators: dict[Any, Callable[[Any, Any], Any]] | None = ...,
            placeholders: Mapping[Any, Matcher[Any] | Callable[[Any], object]] | None = ...,
        ) -> AssertionOutcome: ...

        def matches_contract_snapshot(self, id: str | None = ..., path: str = ...) -> AssertionOutcome: ...

        def matches_inline(
            self,
            expected: object = ...,
            *,
            ignore: _KeySpecs | None = ...,
            include: _KeySpecs | None = ...,
            tolerance: float | None = ...,
            comparators: dict[Any, Callable[[Any, Any], Any]] | None = ...,
            placeholders: Mapping[Any, Matcher[Any] | Callable[[Any], object]] | None = ...,
        ) -> AssertionOutcome: ...
