from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import datetime
    from collections.abc import Callable, Hashable, Iterable, Mapping
    from pathlib import Path
    from typing import Any, ClassVar, Protocol, SupportsFloat, TypeVar, overload

    from typing_extensions import TypeIs

    from .._engine._introspection import MappingLike
    from ..assertpy import AssertionBuilder, CheckBuilder
    from ..async_assertions import AsyncAssertionBuilder, SyncAssertionBuilder
    from ..matchers import Matcher
    from ._compat import Self

    # ``ignore``/``include`` accept a single key, a nested-path tuple, or a list/set/frozenset of them.
    _KeySpecs = Hashable | list[Hashable] | set[Hashable] | frozenset[Hashable]

    _E = TypeVar("_E")  # tracked element type of a collection assertion
    _R = TypeVar("_R")  # result element type after a mapping pivot
    _N = TypeVar("_N", int, float)  # tracked numeric type, so value keeps int or float
    _K = TypeVar("_K")  # tracked dict key type
    _V = TypeVar("_V")  # tracked dict value type
    _B_co = TypeVar("_B_co", bytes, bytearray, covariant=True)  # tracked bytes type (output-only -> covariant)
    _U = TypeVar("_U")  # the type a TypeIs predicate refines the tracked value to
    _T_co = TypeVar("_T_co", covariant=True)  # the subject of a value no overload recognises

    # a capability rather than a list of types: the list said `float | Decimal | Fraction` and refused
    # `numpy.int64`. `str`, `complex`, `date` and containers have no `__float__` and stay caught
    _Number = SupportsFloat

    # Predicates read `Callable[[Any], object]`, or `[Any, Any]` where the runtime hands over a pair.
    # The verdict is `object` and not `bool`, which refused a `numpy.bool_`.

    class _MembershipAssertion(Protocol):
        """ "Is every one of my elements in there", asked the same way by three types.

        `*supersets` is `object`, and that is measured rather than lazy.  The runtime compares by `==`,
        so a superset of a wider element type works: `list[Dog]` against `list[Animal]`, `[1]` against
        `1.0`, a `list[object]` holding the right values.  Both narrowings tried, `Iterable[_E]` and
        `Iterable[_E] | _E`, refused those, and the first also refused the documented
        `is_subset_of(1, 2, 3)` that our own suite calls.

        The mapping view declares its own, because there the runtime refuses a shape by name rather
        than by comparison.  `contains` stays out for the older reason: a string means `str | Matcher`
        by it, and lifting the untyped form once widened the string by accident.
        """

        def is_subset_of(self, *supersets: object, allow_empty: bool = ...) -> Self: ...

    class _SizedAssertion(Protocol):
        """What every value with a length can be asked, declared once instead of in four protocols.

        Not on `_CoreAssertion`, because a number has no length and offering `is_empty()` on one would be
        the false promise this whole file exists to avoid.  Not generated either: a protocol that other
        protocols inherit is the language's own way of saying "these share a capability", and a checker
        understands it without anything being generated, recorded or kept in step.
        """

        def has_same_size_as(self, other: object) -> Self: ...
        def has_size_greater_than(self, size: int) -> Self: ...
        def has_size_less_than(self, size: int) -> Self: ...
        def has_size_between(self, low: int, high: int) -> Self: ...
        def is_empty(self) -> Self: ...
        def is_not_empty(self) -> Self: ...

    class _FilesystemAssertion(Protocol):
        """What a value naming a place on disk can be asked.

        Carried by both the string and the path protocols, because a path is written as a `str` at least
        as often as it is written as a `Path`, and refusing one of the two spellings would be a rule
        that exists only in the type checker.
        """

        def exists(self) -> Self: ...
        def does_not_exist(self) -> Self: ...
        def is_file(self) -> Self: ...
        def is_directory(self) -> Self: ...
        def is_named(self, filename: str) -> Self: ...
        def is_child_of(self, parent: object) -> Self: ...
        def is_readable(self) -> Self: ...
        def is_writable(self) -> Self: ...
        def is_executable(self) -> Self: ...

    class _RealNumberAssertion(Protocol):
        """What a real number can be asked, whether it is spelled `int`, `float` or `bool`.

        `bool` is here because it is an `int` in Python, and an assertion that works on one works on the
        other; leaving it out would be a distinction the runtime does not make.
        """

        def is_positive(self) -> Self: ...
        def is_negative(self) -> Self: ...
        def is_nan(self) -> Self: ...
        def is_not_nan(self) -> Self: ...
        def is_inf(self) -> Self: ...
        def is_not_inf(self) -> Self: ...
        def is_close_to(self, other: _Number, tolerance: _Number) -> Self: ...
        def is_not_close_to(self, other: _Number, tolerance: _Number) -> Self: ...
        def is_not_between(self, low: _Number, high: _Number) -> Self: ...
        def is_between(self, low: _Number, high: _Number) -> Self: ...
        def is_greater_than(self, other: _Number) -> Self: ...
        def is_greater_than_or_equal_to(self, other: _Number) -> Self: ...
        def is_less_than(self, other: _Number) -> Self: ...
        def is_less_than_or_equal_to(self, other: _Number) -> Self: ...

    class _WalkAssertion(Protocol):
        """The quantifiers and the extraction pivot, which anything walkable answers.

        Apart from the JSON family below because the two domains are not the same: a frame walks
        and is not a document, and offering it `at_json_path` promises a refusal.  `_StructureAssertion`
        keeps both together for the mapping and sequence views, which are inside both.
        """

        def extracting(
            self,
            # a selector stays `object`: whether one works depends on the row, and every narrowing tried
            # refused working code, down to `Hashable | slice` refusing a list key
            name: object,
            *names: object,
            # named rather than `**kwargs`, so a typo like `filtr=` is caught before the run.  `Mapping`
            # because `dict` is invariant, and `str` keys because other keys are accepted then skipped
            filter: str | Mapping[str, object] | Callable[[Any], object] = ...,  # noqa: A002  # public keyword
            # `sort` is narrower by the runtime's own rule: a single index is refused, the same index
            # inside a list is honoured
            sort: str | Iterable[object] | Callable[[Any], object] = ...,
        ) -> _ListAssertion[Any]: ...
        def each(self, matcher: Matcher[Any] | Callable[[Any], object], *, allow_empty: bool = ...) -> Self: ...
        def all_satisfy(self, matcher: Matcher[Any] | Callable[[Any], object], *, allow_empty: bool = ...) -> Self: ...

    class _JsonAssertion(Protocol):
        """The document family, for a value the JSON assertions accept: a `dict` or a `list`."""

        def at_json_path(self, path: str) -> _CoreAssertion:
            """Navigate into the document and continue on whatever is there.

            A path lands on an object, an array, a string, a number, a boolean or a null, and which one
            it is lives in the document rather than in any type.  So what comes back offers the
            assertions every value can answer, and nothing beyond them: naming a shape here is what
            offered `contains_key` on an `int` and made a type check pass on a call that raises.

            Reaching further is a narrowing the caller states: a matcher, or a `TypeIs` predicate that
            carries the type into the rest of the chain.  What runs is the predicate, and what is read
            is its boolean answer, so the declared narrowing is taken on trust from whoever wrote it.
            """
            ...

        def has_json_path(self, path: str) -> Self: ...
        def does_not_have_json_path(self, path: str) -> Self: ...
        def matches_json_schema(self, schema: dict[str, Any]) -> Self: ...
        def matches_json_schema_from_file(self, path: str | Path) -> Self: ...
        def conforms_to_openapi(
            self,
            spec: dict[str, Any],
            path: str,
            method: str,
            *,
            status: str | int | None = ...,
            content_type: str = ...,
        ) -> Self: ...

    class _StructureAssertion(_WalkAssertion, _JsonAssertion, Protocol):
        """Quantifiers, the JSON family and the two pivots, which a mapping and a sequence share.

        That sharing is what a JSON document is made of, and the reason these never belonged to
        either one alone.  Kept as one name so the views that are inside both domains compose it
        rather than listing halves.
        """

    class _RepeatableAssertion(Protocol[_E]):
        """What a value with repeatable elements can be asked about its repeats and their order.

        Generic over the element, and that is not decoration: `contains_in_order` names the element type,
        so a protocol without the parameter leaves `_E` free and lets a list of integers be asked about
        strings.  Each carrier binds it to what its own elements are.
        """

        def contains_duplicates(self) -> Self: ...
        def does_not_contain_duplicates(self) -> Self: ...
        def contains_only_once(self, *items: object) -> Self: ...
        def contains_in_order(self, *items: _E | Matcher[_E]) -> Self: ...

    class _ZeroAssertion(Protocol):
        """Zero and its negation, which every numeric spelling shares, complex included."""

        def is_zero(self) -> Self: ...
        def is_not_zero(self) -> Self: ...

    class _CoreAssertion(Protocol):
        """Base protocol with assertions available for all types."""

        # BaseMixin
        def described_as(self, description: str) -> Self: ...
        def is_equal_to(
            self,
            other: object,
            *,
            ignore: _KeySpecs | None = ...,
            include: _KeySpecs | None = ...,
            tolerance: float | None = ...,
            comparators: dict[object, Callable[[Any, Any], object]] | None = ...,
            ignore_null: bool = ...,
            strict_types: bool = ...,
        ) -> Self: ...
        def is_not_equal_to(self, other: object) -> Self: ...
        def is_same_as(self, other: object) -> Self: ...
        def is_not_same_as(self, other: object) -> Self: ...
        def is_true(self) -> Self: ...
        def is_false(self) -> Self: ...
        def is_none(self) -> Self: ...
        def is_not_none(self) -> Self: ...
        def is_type_of(self, some_type: type) -> Self: ...
        # not the narrowing pair the generic fallback carries: refining by class from an already
        # concrete type has no caller, and it would cost two `reportOverlappingOverload`
        def is_instance_of(self, some_class: type) -> Self: ...
        def is_instance_of_any(self, *some_classes: type) -> Self: ...
        def is_subclass_of(self, some_class: type) -> Self: ...
        def is_length(self, length: int) -> Self: ...
        def is_length_between(self, low: int, high: int) -> Self: ...
        def is_callable(self) -> Self: ...
        def is_not_callable(self) -> Self: ...
        # a fair question about any value, not a domain error, so it is held here rather than copied
        # into eleven protocols
        def is_iterable(self) -> Self: ...
        def is_not_iterable(self) -> Self: ...
        # the same refinement the generic fallback offers, so a domain predicate narrows the chain
        # from a concretely typed value too, not only from the untyped one
        # `satisfies` answers with the view the factory would have given for the guarded type, so a
        # refinement is a step in a chain rather than the end of one.  The ladder is written out in
        # each protocol that declares `satisfies`, because a protocol overriding it has to restate the
        # whole overload set, and two of them do in order to narrow the matcher to their own value
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[str]]) -> _StringAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[bool]]) -> _BoolAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[int]]) -> _NumericAssertion[int]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[float]]) -> _NumericAssertion[float]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[complex]]) -> _ComplexAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[dict[_K, _V]]]) -> _DictAssertion[_K, _V]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[list[_E] | tuple[_E, ...]]]) -> _IterableAssertion[_E]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[set[_E] | frozenset[_E]]]) -> _IterableAssertion[_E]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[datetime.date]]) -> _DateAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[Path]]) -> _PathAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[bytes]]) -> _BytesAssertion[bytes]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[bytearray]]) -> _BytesAssertion[bytearray]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[Callable[..., object]]]) -> _CallableAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[_CapableT]]) -> AssertionBuilder[_CapableT]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[_U]]) -> _ObjectAssertion[_U]: ...
        @overload
        def satisfies(self, matcher: Matcher[Any] | Callable[[Any], object]) -> Self: ...
        def all_fields_satisfy(
            self, matcher: Matcher[Any] | Callable[[Any], object], *, allow_empty: bool = ...
        ) -> Self: ...
        def has_no_none_fields(self, *, allow_empty: bool = ...) -> Self: ...
        # ContainsMixin - universal
        def is_in(self, *items: object) -> Self: ...
        def is_not_in(self, *items: object) -> Self: ...
        # SnapshotMixin
        def snapshot(
            self,
            id: str | None = ...,  # noqa: A002  # mirrors public snapshot() parameter
            path: str = ...,
            *,
            ignore: _KeySpecs | None = ...,
            include: _KeySpecs | None = ...,
            tolerance: float | None = ...,
            comparators: dict[object, Callable[[Any, Any], object]] | None = ...,
            placeholders: dict[Hashable, Matcher[Any] | Callable[[Any], object]] | None = ...,
        ) -> Self: ...
        def matches_contract_snapshot(self, id: str | None = ..., path: str = ...) -> Self: ...  # noqa: A002  # mirrors public parameter
        def matches_inline(
            self,
            expected: object = ...,
            *,
            ignore: _KeySpecs | None = ...,
            include: _KeySpecs | None = ...,
            tolerance: float | None = ...,
            comparators: dict[object, Callable[[Any, Any], object]] | None = ...,
            placeholders: dict[Hashable, Matcher[Any] | Callable[[Any], object]] | None = ...,
        ) -> Self: ...
        # NegatedBuilder, which a checker sees as this very protocol: the proxy accepts what the
        # value accepts and hands the chain back, so describing it any other way is what let
        # `assert_that(1).not_.starts_with("x")` type-check
        @property
        def not_(self) -> Self: ...
        # CheckBuilder - run the next assertion for its verdict instead of for its failure
        def check(self) -> CheckBuilder: ...
        # AssertionBuilder - typed extract-and-continue
        @property
        def value(self) -> object: ...

    class _ObjectAssertion(_CoreAssertion, Protocol[_T_co]):
        """What a value no overload recognises can be asked, which is the core surface and ordering.

        The fallback used to hand back the builder itself, carrying all 152 assertion names, so
        `assert_that(Person()).is_positive()` type-checked and then raised.  This is the other end: a
        value with no capability any overload can see gets what applies to every value.

        Ordering is here and not in `_CoreAssertion`, and the difference matters.  Every other view
        spells its own operand (`str` against `str`, a date against a date), which is what makes the
        comparison worth checking, and a frame is refused outright.  Only an unrecognised value has no
        operand to name, so it takes `object` and judges anything.  That is a recorded boundary rather
        than an oversight: `tests/typing_negative_baseline.py` holds why every narrower spelling trades
        a correct call for an incorrect one, and a `Decimal` compared against an `int` is the case it
        would break.

        The three refinements are declared here rather than inherited because they have to return this
        view: they are the reason `.value` can be read without a `cast()`, and a refinement that came
        back as the builder would put all 152 names back at the first `is_not_none()`.
        """

        @property
        def value(self) -> _T_co: ...

        # `matches_structure` for the same reason as ordering, one level further down.  Its subject is
        # a mapping, a pydantic-style model or an attrs instance, and the last of those is invisible:
        # `__attrs_attrs__` reaches mypy, which has a plugin for it, and neither ty nor pyright.  A
        # shape keyed on it would answer three different ways, which is worse than answering widely
        def matches_structure(self, spec: dict) -> Self: ...

        # ordering, with an operand of any type. See the class docstring for why it is not narrower
        def is_greater_than(self, other: Any) -> Self: ...
        def is_greater_than_or_equal_to(self, other: Any) -> Self: ...
        def is_less_than(self, other: Any) -> Self: ...
        def is_less_than_or_equal_to(self, other: Any) -> Self: ...
        def is_between(self, low: Any, high: Any) -> Self: ...
        def is_not_between(self, low: Any, high: Any) -> Self: ...

        # The refinements: strip `None`, narrow to a class, follow a `TypeIs` predicate.  Each answers
        # with the view `assert_that()` would have given for the refined type, as far as each checker
        # solves it (see the measurement below), and the ladder is
        # that overload set written a second time, because nothing reapplies an overload set to a
        # TypeVar.  Without it a refinement is a dead end: `.value` comes back typed and the chain has
        # lost the type's own assertions, so a `str | None` asked `is_not_none()` could no longer be
        # asked `starts_with`.
        #
        # It closes a hole as well as repairing one.  These used to hand back the builder, so
        # `assert_that(thing).is_instance_of(Person).is_positive()` type-checked.
        #
        # "the view the factory would have given" is measured against the factory, not asserted:
        # mypy and pyright answer identically for all twelve types, and ty resolves eight and answers
        # `Unknown` for the numeric and sequence rungs without reporting anything.  `Unknown` accepts
        # every call, so what is lost there is the narrowing rather than a working call.
        # `bool` before `int`, as in the factory: a `bool` is an `int` and the first match wins.
        #
        # No rung for a shape, and the reason is measured rather than assumed.  Two spellings were
        # tried and each puts a different checker in the wrong.  With a bound type variable, mypy
        # solves it to `Never` against an `object` subject and takes the rung anyway, handing the
        # whole builder to the value this narrowing exists for.  With the shape union written out,
        # mypy and pyright are right and ty takes it for `object` instead.  So `Bag | None` asked
        # `is_not_none()` gets this view rather than the builder, and the way back to the wider
        # surface is `.value` or a `TypeIs` predicate, which names its target and does not
        # degenerate.  One answer from three checkers is worth more than a better answer from one.
        @overload
        def is_not_none(self: _ObjectAssertion[str | None]) -> _StringAssertion: ...
        @overload
        def is_not_none(self: _ObjectAssertion[bool | None]) -> _BoolAssertion: ...
        @overload
        def is_not_none(self: _ObjectAssertion[int | None]) -> _NumericAssertion[int]: ...
        @overload
        def is_not_none(self: _ObjectAssertion[float | None]) -> _NumericAssertion[float]: ...
        @overload
        def is_not_none(self: _ObjectAssertion[complex | None]) -> _ComplexAssertion: ...
        @overload
        def is_not_none(self: _ObjectAssertion[dict[_K, _V] | None]) -> _DictAssertion[_K, _V]: ...
        @overload
        def is_not_none(self: _ObjectAssertion[list[_E] | tuple[_E, ...] | None]) -> _IterableAssertion[_E]: ...
        @overload
        def is_not_none(self: _ObjectAssertion[set[_E] | frozenset[_E] | None]) -> _IterableAssertion[_E]: ...
        @overload
        def is_not_none(self: _ObjectAssertion[datetime.date | None]) -> _DateAssertion: ...
        @overload
        def is_not_none(self: _ObjectAssertion[Path | None]) -> _PathAssertion: ...
        @overload
        def is_not_none(self: _ObjectAssertion[bytes | None]) -> _BytesAssertion[bytes]: ...
        @overload
        def is_not_none(self: _ObjectAssertion[bytearray | None]) -> _BytesAssertion[bytearray]: ...
        @overload
        def is_not_none(self: _ObjectAssertion[Callable[..., object] | None]) -> _CallableAssertion: ...
        @overload
        def is_not_none(self: _ObjectAssertion[_U | None]) -> _ObjectAssertion[_U]: ...
        @overload
        def is_not_none(self) -> Self: ...
        @overload
        def is_instance_of(self, some_class: type[str]) -> _StringAssertion: ...
        @overload
        def is_instance_of(self, some_class: type[bool]) -> _BoolAssertion: ...
        @overload
        def is_instance_of(self, some_class: type[int]) -> _NumericAssertion[int]: ...
        @overload
        def is_instance_of(self, some_class: type[float]) -> _NumericAssertion[float]: ...
        @overload
        def is_instance_of(self, some_class: type[complex]) -> _ComplexAssertion: ...
        @overload
        def is_instance_of(self, some_class: type[dict[_K, _V]]) -> _DictAssertion[_K, _V]: ...
        @overload
        def is_instance_of(self, some_class: type[list[_E] | tuple[_E, ...]]) -> _IterableAssertion[_E]: ...
        @overload
        def is_instance_of(self, some_class: type[set[_E] | frozenset[_E]]) -> _IterableAssertion[_E]: ...
        @overload
        def is_instance_of(self, some_class: type[datetime.date]) -> _DateAssertion: ...
        @overload
        def is_instance_of(self, some_class: type[Path]) -> _PathAssertion: ...
        @overload
        def is_instance_of(self, some_class: type[bytes]) -> _BytesAssertion[bytes]: ...
        @overload
        def is_instance_of(self, some_class: type[bytearray]) -> _BytesAssertion[bytearray]: ...
        @overload
        def is_instance_of(self, some_class: type[_U]) -> _ObjectAssertion[_U]: ...
        @overload
        def is_instance_of(self, some_class: type) -> Self: ...

    class _TextAssertion(_MembershipAssertion, _RepeatableAssertion[str], _SizedAssertion, _CoreAssertion, Protocol):
        """What a piece of text can be asked, whether a caller passed it in or the library caught it.

        Split out from the string view so the invoked view can share it without sharing the rest.  The
        message a raised exception hands back is a `str`, so every assertion here applies to it, and
        the assertions that read a path do not: that inheritance offered `exists()` on the text of an
        exception, which the runtime then looks for on disk.
        """

        # narrowed from the core: the value under test is a `str`, so a matcher built for another type
        # is a type error here rather than something only the runtime discovers
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[str]]) -> _StringAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[bool]]) -> _BoolAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[int]]) -> _NumericAssertion[int]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[float]]) -> _NumericAssertion[float]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[complex]]) -> _ComplexAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[dict[_K, _V]]]) -> _DictAssertion[_K, _V]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[list[_E] | tuple[_E, ...]]]) -> _IterableAssertion[_E]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[set[_E] | frozenset[_E]]]) -> _IterableAssertion[_E]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[datetime.date]]) -> _DateAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[Path]]) -> _PathAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[bytes]]) -> _BytesAssertion[bytes]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[bytearray]]) -> _BytesAssertion[bytearray]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[Callable[..., object]]]) -> _CallableAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[_CapableT]]) -> AssertionBuilder[_CapableT]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[_U]]) -> _ObjectAssertion[_U]: ...
        @overload
        def satisfies(self, matcher: Matcher[str] | Callable[[Any], object]) -> Self: ...

        """Assertions available for ``str`` values."""

        def contains(self, *items: str | Matcher[str]) -> Self: ...

        @property
        def value(self) -> str: ...
        # StringMixin
        def is_equal_to_ignoring_case(self, other: str) -> Self: ...
        def is_equal_to_ignoring_whitespace(self, other: str) -> Self: ...
        def contains_ignoring_case(self, *items: str) -> Self: ...
        def starts_with(self, prefix: str) -> Self: ...
        def starts_with_ignoring_case(self, prefix: str) -> Self: ...
        def ends_with(self, suffix: str) -> Self: ...
        def ends_with_ignoring_case(self, suffix: str) -> Self: ...
        def matches(self, pattern: str) -> Self: ...
        def does_not_match(self, pattern: str) -> Self: ...
        def is_alpha(self) -> Self: ...
        def is_digit(self) -> Self: ...
        def is_lower(self) -> Self: ...
        def is_upper(self) -> Self: ...
        def is_alphanumeric(self) -> Self: ...
        def is_whitespace(self) -> Self: ...
        def contains_any_of(self, *items: str) -> Self: ...
        def contains_none_of(self, *items: str) -> Self: ...
        def is_unicode(self) -> Self: ...
        # NumericMixin - lexicographic ordering
        def is_greater_than(self, other: str) -> Self: ...
        def is_greater_than_or_equal_to(self, other: str) -> Self: ...
        def is_less_than(self, other: str) -> Self: ...
        def is_less_than_or_equal_to(self, other: str) -> Self: ...
        # ContainsMixin, bound to `str`: every one of these takes a substring, and a matcher stands in
        # for one wherever a substring is accepted
        def does_not_contain(self, *items: str | Matcher[str]) -> Self: ...
        def contains_only(self, *items: str | Matcher[str]) -> Self: ...
        def contains_sequence(self, *items: str | Matcher[str]) -> Self: ...
        def contains_exactly(self, *items: str | Matcher[str]) -> Self: ...
        def contains_exactly_in_any_order(self, *items: str | Matcher[str]) -> Self: ...
        # a string is walked character by character, so the key sees a one-character `str`
        def is_sorted(
            self, key: Callable[[str], object] = ..., reverse: bool = ..., *, allow_empty: bool = ...
        ) -> Self: ...
        # CollectionMixin - pipeline.  A character of a string is a string, so the element pivots stay on
        # this protocol instead of widening to the generic builder, which would hand a one-character
        # value the whole API back
        def filtered_on(self, predicate: Matcher[str] | Callable[[str], object]) -> _ListAssertion[str]: ...
        def mapped(self, func: Callable[[str], _R]) -> _ListAssertion[_R]: ...
        def flat_mapped(self, func: Callable[[str], Iterable[_R]]) -> _ListAssertion[_R]: ...
        # a character of a text is text, and nothing more: returning the string view here handed the
        # filesystem assertions back to a message through `.first()`, which is the promise the split
        # removed one step earlier
        def first(self) -> _TextAssertion: ...
        def last(self) -> _TextAssertion: ...
        def element(self, index: int) -> _TextAssertion: ...
        def single(self) -> _TextAssertion: ...
        # StringMixin - regex
        def extracting_group(self, pattern: str, group: int | str = ...) -> Self: ...
        # a tuple for positional groups, a dict for named ones: which cannot be known from the pattern
        # statically, so the chain continues on the untyped builder rather than pretending it is a str
        def matches_with_groups(self, pattern: str) -> AssertionBuilder[Any]: ...

    class _StringAssertion(_TextAssertion, _FilesystemAssertion, Protocol):
        """Assertions available for ``str`` values.

        The text assertions plus the ones that read the value as a path, because a path is written as a
        `str` at least as often as it is written as a `Path`.
        """

        # redeclared so a pivot keeps its result a `str`: the inherited form returns the text
        # capability, which is what a caught message needs and what keeps `exists()` away from it
        def first(self) -> _StringAssertion: ...
        def last(self) -> _StringAssertion: ...
        def element(self, index: int) -> _StringAssertion: ...
        def single(self) -> _StringAssertion: ...

        # FileMixin

    class _NumericAssertion(_RealNumberAssertion, _ZeroAssertion, _CoreAssertion, Protocol[_N]):
        """Assertions available for ``int`` and ``float`` values.

        Generic over the number type ``_N`` so ``value`` keeps the exact numeric type instead of the
        ``int | float`` union.

        `complex` and `bool` have protocols of their own, each carrying what the runtime actually
        accepts for that type rather than the whole numeric set.
        """

        @property
        def value(self) -> _N: ...
        # narrowed from the core, for the same reason the string protocol narrows it
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[str]]) -> _StringAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[bool]]) -> _BoolAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[int]]) -> _NumericAssertion[int]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[float]]) -> _NumericAssertion[float]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[complex]]) -> _ComplexAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[dict[_K, _V]]]) -> _DictAssertion[_K, _V]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[list[_E] | tuple[_E, ...]]]) -> _IterableAssertion[_E]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[set[_E] | frozenset[_E]]]) -> _IterableAssertion[_E]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[datetime.date]]) -> _DateAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[Path]]) -> _PathAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[bytes]]) -> _BytesAssertion[bytes]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[bytearray]]) -> _BytesAssertion[bytearray]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[Callable[..., object]]]) -> _CallableAssertion: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[_CapableT]]) -> AssertionBuilder[_CapableT]: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[_U]]) -> _ObjectAssertion[_U]: ...
        @overload
        def satisfies(self, matcher: Matcher[_N] | Callable[[Any], object]) -> Self: ...
        # `_Number` rather than `_N`: comparing an `int` against a `float` is ordinary and has to keep
        # working, while comparing either against text is the mistake worth catching. `Decimal` and
        # `Fraction` are named because the stdlib's own numbers do not form a static hierarchy
        def is_even(self) -> Self: ...
        def is_odd(self) -> Self: ...
        def is_divisible_by(self, divisor: int) -> Self: ...

    class _ComplexAssertion(_ZeroAssertion, _CoreAssertion, Protocol):
        """Assertions available for ``complex`` values, which is far fewer than for a real number.

        Ordering is not defined for a complex number, and neither is parity, divisibility, NaN or
        infinity: the runtime refuses all thirteen of those with `TypeError: ordering is not defined for
        type <complex>` and its relatives.  It used to advertise them anyway, because `complex` shared
        the numeric protocol, so a checker suggested a method whose only outcome was a crash.
        """

        @property
        def value(self) -> complex: ...

    class _BoolAssertion(_RealNumberAssertion, _ZeroAssertion, _CoreAssertion, Protocol):
        """Assertions available for ``bool``, which is every numeric one except the integer-only three.

        `bool` is a subclass of `int`, so it used to resolve to the numeric protocol and be offered
        `is_even`, `is_odd` and `is_divisible_by`.  The runtime refuses exactly those three with
        `TypeError: val is not an integer, got bool`, and accepts the rest: `True > 0` is a real
        comparison.  The type now says the same thing.
        """

        @property
        def value(self) -> bool: ...

    class _IterableAssertion(
        _MembershipAssertion,
        _StructureAssertion,
        _RepeatableAssertion[_E],
        _SizedAssertion,
        _CoreAssertion,
        Protocol[_E],
    ):
        """Assertions available for ``list``, ``tuple``, ``set``, and ``frozenset`` values.

        Generic over the element type ``_E`` so element-access pivots (``first``/``last``/``element``/
        ``single``) narrow the chain to the element, and ``value`` keeps the element type.
        """

        @property
        def value(self) -> list[_E] | tuple[_E, ...] | set[_E] | frozenset[_E]: ...
        # ContainsMixin, bound to the element type: an item of another type can never be in there, and
        # a matcher stands in for an item wherever one is accepted
        def contains(self, *items: _E | Matcher[_E]) -> Self: ...
        def does_not_contain(self, *items: _E | Matcher[_E]) -> Self: ...
        def contains_only(self, *items: _E | Matcher[_E]) -> Self: ...
        def contains_sequence(self, *items: _E | Matcher[_E]) -> Self: ...
        def contains_exactly(self, *items: _E | Matcher[_E]) -> Self: ...
        def contains_exactly_in_any_order(self, *items: _E | Matcher[_E]) -> Self: ...
        # CollectionMixin - the iterable pair lives on the core protocol, where every value can ask it
        def is_sorted(
            self, key: Callable[[_E], object] = ..., reverse: bool = ..., *, allow_empty: bool = ...
        ) -> Self: ...
        # StringMixin - both work on any ordered sequence, not just str, and the docs show them on lists
        def starts_with(self, prefix: _E) -> Self: ...
        def ends_with(self, suffix: _E) -> Self: ...
        # BaseMixin
        # narrowed from the structure capability, which cannot know the element: here it is _E
        def each(self, matcher: Matcher[_E] | Callable[[_E], object], *, allow_empty: bool = ...) -> Self: ...
        def all_satisfy(self, matcher: Matcher[_E] | Callable[[_E], object], *, allow_empty: bool = ...) -> Self: ...
        def any_satisfy(self, matcher: Matcher[_E] | Callable[[_E], object]) -> Self: ...
        def none_satisfy(self, matcher: Matcher[_E] | Callable[[_E], object]) -> Self: ...
        def satisfies_exactly(self, *matchers: Matcher[_E] | Callable[[_E], object]) -> Self: ...
        def satisfies_exactly_in_any_order(self, *matchers: Matcher[_E] | Callable[[_E], object]) -> Self: ...
        def zip_satisfies(
            self, other: Iterable[object], predicate: Callable[[Any, Any], object], *, allow_empty: bool = ...
        ) -> Self: ...
        # CollectionMixin - pipeline (filter keeps the element type; map changes it; access yields the element)
        def filtered_on(self, predicate: Matcher[_E] | Callable[[_E], object]) -> _ListAssertion[_E]: ...
        def mapped(self, func: Callable[[_E], _R]) -> _ListAssertion[_R]: ...
        def flat_mapped(self, func: Callable[[_E], Iterable[_R]]) -> _ListAssertion[_R]: ...
        def first(self) -> AssertionBuilder[_E]: ...
        def last(self) -> AssertionBuilder[_E]: ...
        def element(self, index: int) -> AssertionBuilder[_E]: ...
        def single(self) -> AssertionBuilder[_E]: ...

    class _ListAssertion(_IterableAssertion[_E], Protocol[_E]):
        """The iterable view of a collection this library built, rather than one a caller passed in.

        Every pipeline step returns one of these, and the difference from `_IterableAssertion` is a single
        line: `value` is a `list`, not one of four containers.  That is not a guess.  `filtered_on`,
        `mapped`, `flat_mapped` and `extracting` build a list whatever they were given, on a `tuple`, a
        `set` and a `frozenset` alike, so declaring the union afterwards described an input that has
        already been left behind, and made callers narrow a type the library had already settled.
        """

        @property
        def value(self) -> list[_E]: ...

    class _DictAssertion(_StructureAssertion, _SizedAssertion, _CoreAssertion, Protocol[_K, _V]):
        """Assertions available for ``dict`` values, generic over the key and value types."""

        # the one view where narrowing holds, since the runtime refuses a superset without `keys()`.
        # Both spellings, as neither covers the other, and neither key nor value is bound
        def is_subset_of(self, *supersets: Mapping[Any, Any] | MappingLike, allow_empty: bool = ...) -> Self: ...

        def contains(self, *items: object) -> Self: ...

        @property
        def value(self) -> dict[_K, _V]: ...
        # DictMixin
        # narrowed from the structure capability, which cannot know the element: here it is _K
        def each(self, matcher: Matcher[_K] | Callable[[_K], object], *, allow_empty: bool = ...) -> Self: ...
        def all_satisfy(self, matcher: Matcher[_K] | Callable[[_K], object], *, allow_empty: bool = ...) -> Self: ...
        def contains_key(self, *keys: _K | Matcher[_K]) -> Self: ...
        def does_not_contain_key(self, *keys: _K | Matcher[_K]) -> Self: ...
        def contains_value(self, *values: _V | Matcher[_V]) -> Self: ...
        def does_not_contain_value(self, *values: _V | Matcher[_V]) -> Self: ...
        def contains_entry(self, *args: object, **kwargs: object) -> Self: ...
        def does_not_contain_entry(self, *args: object, **kwargs: object) -> Self: ...
        # ContainsMixin
        def does_not_contain(self, *items: object) -> Self: ...
        def contains_only(self, *keys: object) -> Self: ...
        # CollectionMixin - a dict is compared against other dicts, key by key
        # iterating a dict yields its keys, so that is what the sort key is handed
        def is_sorted(
            self, key: Callable[[_K], object] = ..., reverse: bool = ..., *, allow_empty: bool = ...
        ) -> Self: ...
        # CollectionMixin - pipeline over the keys.  The element pivots hand back the generic builder
        # rather than a narrowed view: a key is of an arbitrary type `_K`, and turning an arbitrary type
        # into the protocol `assert_that` would pick for it is the type-level dispatch this API lacks
        def filtered_on(self, predicate: Matcher[_K] | Callable[[_K], object]) -> _ListAssertion[_K]: ...
        def mapped(self, func: Callable[[_K], _R]) -> _ListAssertion[_R]: ...
        def flat_mapped(self, func: Callable[[_K], Iterable[_R]]) -> _ListAssertion[_R]: ...
        def first(self) -> AssertionBuilder[_K]: ...
        def last(self) -> AssertionBuilder[_K]: ...
        def element(self, index: int) -> AssertionBuilder[_K]: ...
        def single(self) -> AssertionBuilder[_K]: ...
        # BaseMixin
        def matches_structure(self, spec: dict) -> Self: ...

        # the same quantifier under its other name, which delegates here.  Declared alongside rather
        # than only on the sequence view: a delegate reachable in fewer places than what it delegates
        # to is a difference the runtime does not have

    # --- the shapes a checker can recognise without importing the library that defines them ---------
    #
    # These describe a value by what it carries, so no optional dependency is named in a signature and a
    # user without pandas installed still type-checks against the same package.
    #
    # Every member here is one `pandas-stubs` actually declares.  The dataframe interchange method
    # `__dataframe__` reads better and does not work: the stubs do not declare it, so it arrives through
    # their catch-all as a `Series[Any]`, and mypy then read a frame as not matching and resolved it to
    # the array view instead.  `pivot` is declared, both libraries have it on their frame, and neither a
    # series nor a `pandas.Index` does - which matters, because an `Index` carries `join`, `to_frame`
    # and `dtype` and would otherwise be offered assertions the runtime refuses it.
    #
    # There is deliberately no series shape.  Nothing separates a series from a `pandas.Index`, both
    # carrying `to_frame` and `dtype`, so a series keeps the generic builder it has always had rather
    # than buying a narrower view at the price of promising an `Index` something it cannot do.
    #
    # `strides` rather than `dtype` on the array for the same reason from the other side: a series and
    # an `Index` both carry `__array__` and `dtype`, and the array view has no `is_frame_equal`, which
    # the runtime accepts for a series.  A narrower view that removes a working call is worse than the
    # builder they have today.

    # The capability umbrella.  Between the fifteen typed overloads and the fallback sits one more,
    # for a value that answers to *some* capability the library recognises without being a type any
    # overload names: a custom collection, an HTTP response from any of the six clients, a pydantic
    # model, an attrs instance, a dataclass, a mapping that is not a `dict`.  Those keep the whole
    # surface, and only a value with no capability at all is narrowed.
    #
    # One overload rather than one per family, because a family-precise view is a permanent claim about
    # what that family may be asked, and the frame pair is the measure of how much work one such claim
    # is.  This is the compatibility half, and a family can be lifted out of the union later when its
    # shape has been shown to hold across the three checkers.
    #
    # Every member is keyed on what the runtime gate reads, not on what reads well.  `__dict__` was the
    # first candidate for the structure member and it is on `object`, so it matched a plain class and
    # would have made the narrowing do nothing while every gate stayed green.

    class _CollectionShape(Protocol):
        # `__iter__` alone: `is_length` lives in the core, and a generator has no `__len__` while
        # `contains()` works on one
        def __iter__(self) -> Any: ...

    class _HeadersShape(Protocol):
        def keys(self) -> Any: ...
        # positional-only: typeshed spells `__getitem__` that way, and a member that also takes the
        # key by name is one no mapping in the standard library satisfies
        def __getitem__(self, key: Any, /) -> Any: ...

    class _HttpResponseShape(Protocol):
        # read-only members, so a client spelling either of these as a property still matches
        @property
        def status_code(self) -> int: ...
        @property
        def headers(self) -> _HeadersShape: ...

    class _ModelShape(Protocol):
        def model_dump(self, *args: Any, **kwargs: Any) -> Any: ...

    class _DataclassShape(Protocol):
        # `ClassVar`, because that is what `__dataclass_fields__` is.  Spelled as an instance variable
        # it matched no dataclass at all, and mypy is the one that says why in as many words
        __dataclass_fields__: ClassVar[Any]

    class _MappingLikeShape(Protocol):
        def keys(self) -> Any: ...
        # positional-only: typeshed spells `__getitem__` that way, and a member that also takes the
        # key by name is one no mapping in the standard library satisfies
        def __getitem__(self, key: Any, /) -> Any: ...

    _CapableT = TypeVar(
        "_CapableT",
        bound=_CollectionShape | _HttpResponseShape | _ModelShape | _DataclassShape | _MappingLikeShape,
    )

    class _FrameShape(Protocol):
        def pivot(self, *args: Any, **kwargs: Any) -> Any: ...
        @property
        def shape(self) -> Any: ...

    class _ArrayShape(Protocol):
        def __array__(self) -> Any: ...
        @property
        def strides(self) -> Any: ...

    # covariant: the view only ever hands the subject back, through `.value`
    _FrameT_co = TypeVar("_FrameT_co", bound=_FrameShape, covariant=True)
    _ArrayT_co = TypeVar("_ArrayT_co", bound=_ArrayShape, covariant=True)

    class _CollectionShapedAssertion(_SizedAssertion, _MembershipAssertion, _WalkAssertion, Protocol):
        """What a frame, a series and an array all answer, measured rather than assumed.

        Every family here is one their runtime gates accept: they are sized, they are walked, and they
        answer membership.  What is deliberately absent is as measured: the JSON family refuses them,
        `matches_structure` refuses a polars frame, and the ordering assertions refuse them through
        `is_between` while `is_greater_than` leaks the library's own ambiguity error instead.

        One boundary the shapes cannot express: a zero-dimensional array carries `__array__` and
        `strides` like any other, and `numpy.ndarray[Any, Any]` covers it, yet it has no length and
        cannot be iterated.  So `is_not_empty`, `is_length`, `contains_only` and `each` are offered on
        `numpy.array(1)` and raise there.  Separating it statically would need a shape keyed on the
        dimension, which the stubs do not carry, and `tests/test_dataframe.py` holds what it does
        instead.
        """

        def contains(self, *items: object) -> Self: ...
        def contains_only(self, *items: object) -> Self: ...

    class _ArrayLikeAssertion(_CollectionShapedAssertion, _CoreAssertion, Protocol):
        """The two numpy assertions, which every array-like the runtime accepts can answer."""

        def is_array_equal(self, expected: object, **options: Any) -> Self: ...
        def is_array_close_to(
            self,
            expected: object,
            *,
            rtol: float = ...,
            atol: float = ...,
            equal_nan: bool = ...,
            **options: Any,
        ) -> Self: ...

    class _FrameAssertion(_ArrayLikeAssertion, Protocol[_FrameT_co]):
        """Assertions available for a pandas or polars frame, which is array-like as well."""

        @property
        def value(self) -> _FrameT_co: ...
        def is_frame_equal(self, expected: object, **options: Any) -> Self: ...

    class _ArrayAssertion(_ArrayLikeAssertion, Protocol[_ArrayT_co]):
        """Assertions available for a numpy array, which is everything a frame has but `is_frame_equal`."""

        @property
        def value(self) -> _ArrayT_co: ...

    class _DateAssertion(_CoreAssertion, Protocol):
        """Assertions available for ``datetime.date`` and ``datetime.datetime`` values."""

        @property
        def value(self) -> datetime.date: ...
        # a date orders against a date, and `datetime` is a `date`, so one annotation covers both
        def is_before(self, other: datetime.date) -> Self: ...
        def is_after(self, other: datetime.date) -> Self: ...
        def is_before_or_equal_to(self, other: datetime.date) -> Self: ...
        def is_after_or_equal_to(self, other: datetime.date) -> Self: ...
        def is_equal_to_ignoring_milliseconds(self, other: object) -> Self: ...
        def is_equal_to_ignoring_seconds(self, other: object) -> Self: ...
        def is_equal_to_ignoring_time(self, other: object) -> Self: ...
        # NumericMixin - chronological ordering; at runtime operands must match val's exact type
        def is_greater_than(self, other: datetime.date) -> Self: ...
        def is_greater_than_or_equal_to(self, other: datetime.date) -> Self: ...
        def is_less_than(self, other: datetime.date) -> Self: ...
        def is_less_than_or_equal_to(self, other: datetime.date) -> Self: ...
        def is_between(self, low: datetime.date, high: datetime.date) -> Self: ...

    class _PathAssertion(_FilesystemAssertion, _CoreAssertion, Protocol):
        """Assertions available for ``pathlib.Path`` values."""

        @property
        def value(self) -> Path: ...

    class _BytesAssertion(_MembershipAssertion, _SizedAssertion, _CoreAssertion, Protocol[_B_co]):
        """Assertions available for ``bytes`` and ``bytearray`` values, generic over which one."""

        def contains(self, *items: object) -> Self: ...

        @property
        def value(self) -> _B_co: ...
        # ContainsMixin
        # CollectionMixin - walking a byte string yields ints, which is what all of these see
        def is_sorted(
            self, key: Callable[[int], object] = ..., reverse: bool = ..., *, allow_empty: bool = ...
        ) -> Self: ...
        def filtered_on(self, predicate: Matcher[int] | Callable[[int], object]) -> _ListAssertion[int]: ...
        def mapped(self, func: Callable[[int], _R]) -> _ListAssertion[_R]: ...
        def flat_mapped(self, func: Callable[[int], Iterable[_R]]) -> _ListAssertion[_R]: ...
        def first(self) -> _NumericAssertion[int]: ...
        def last(self) -> _NumericAssertion[int]: ...
        def element(self, index: int) -> _NumericAssertion[int]: ...
        def single(self) -> _NumericAssertion[int]: ...
        # StringMixin - the prefix/suffix pair handles bytes natively, so a byte string reaches them
        # under their general names as well as under the bytes-only ones below
        def starts_with(self, prefix: bytes | bytearray) -> Self: ...
        def ends_with(self, suffix: bytes | bytearray) -> Self: ...
        # BytesMixin
        def is_valid_utf8(self) -> Self: ...
        def is_valid_encoding(self, encoding: str) -> Self: ...
        def starts_with_bytes(self, prefix: bytes) -> Self: ...
        def contains_bytes(self, sub: bytes) -> Self: ...
        def has_byte_at(self, index: int, expected: int) -> Self: ...
        def is_hex_equal_to(self, expected_hex: str) -> Self: ...
        def decoded_as(self, encoding: str = ...) -> _StringAssertion: ...
        # NumericMixin - lexicographic ordering
        def is_greater_than(self, other: bytes | bytearray) -> Self: ...
        def is_greater_than_or_equal_to(self, other: bytes | bytearray) -> Self: ...
        def is_less_than(self, other: bytes | bytearray) -> Self: ...
        def is_less_than_or_equal_to(self, other: bytes | bytearray) -> Self: ...

    class _InvokedAssertion(_TextAssertion, Protocol):
        """Assertions available after ``when_called_with()`` captured an exception/warning message.

        The captured message is a ``str`` (hence the text assertions, though not the ones reading a
        path: a message is not a filename);
        [`returned()`][assertpy2.exception.ExceptionMixin.returned] pivots to the value the callable
        returned.  Its static type is unknown, so ``returned()`` exposes the
        type-agnostic core assertions (``is_equal_to``, ``is_instance_of``, ``satisfies``, ...) -
        type-safe by construction, never advertising methods that may not apply.
        """

        def returned(self) -> _CoreAssertion: ...
        # raised() pivots to the caught exception object (type-agnostic, like returned());
        # caused_by()/has_root_cause() walk the cause chain and pivot to that cause's message;
        # contains_error() asserts on a caught ExceptionGroup and keeps the chain on it
        def raised(self) -> _CoreAssertion: ...
        def caused_by(self, ex: type) -> Self: ...
        # the group family: `errors()` hands back the leaves as a list, so every collection assertion
        # answers about them, and `error_of()` pivots to one matching node's message, the way `caused_by()`
        # pivots to the cause
        def errors(self) -> _ListAssertion[BaseException]: ...
        # `error_of` keeps the invoked view, the way `caused_by` does: both pivot to a message and both
        # leave the exception reachable through `raised()`, which no plain text view declares
        def error_of(self, ex: type) -> Self: ...
        def does_not_contain_error(self, *ex_types: type) -> Self: ...
        def has_root_cause(self, ex: type) -> Self: ...
        def contains_error(self, *ex_types: type) -> Self: ...

    class _CallableAssertion(_CoreAssertion, Protocol):
        """Assertions available for callable values."""

        @property
        def value(self) -> Callable[..., object]: ...
        def raises(self, ex: type) -> Self: ...
        def does_not_raise(self, ex: type) -> Self: ...
        def warns(self, warning: type[Warning] = ...) -> Self: ...
        def does_not_warn(self, warning: type[Warning] = ...) -> Self: ...
        # captured value (exception or warning message) is a str; returned() pivots to the call result
        def when_called_with(self, *some_args: object, **some_kwargs: object) -> _InvokedAssertion: ...
        def eventually(
            self,
            *,
            timeout: float = ...,
            interval: float = ...,
            ignoring: type[Exception] | tuple[type[Exception], ...] = ...,
            trace: bool = ...,
        ) -> AsyncAssertionBuilder: ...
        def eventually_sync(
            self,
            *,
            timeout: float = ...,
            interval: float = ...,
            ignoring: type[Exception] | tuple[type[Exception], ...] = ...,
            trace: bool = ...,
        ) -> SyncAssertionBuilder: ...
