from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import datetime
    from collections.abc import Callable, Hashable, Iterable, Mapping
    from pathlib import Path
    from typing import Any, Protocol, SupportsFloat, TypeVar, overload

    from typing_extensions import TypeIs

    from ..assertpy import AssertionBuilder, CheckBuilder, NegatedBuilder
    from ..async_assertions import AsyncAssertionBuilder, SyncAssertionBuilder
    from ..matchers import Matcher
    from ._compat import Self

    # ``ignore``/``include`` accept a single key, a nested-path tuple, or a list/set/frozenset of them.
    _KeySpecs = Hashable | list[Hashable] | set[Hashable] | frozenset[Hashable]

    _E = TypeVar("_E")  # tracked element type of a collection assertion
    _R = TypeVar("_R")  # result element type after a mapping pivot
    _N = TypeVar("_N", int, float)  # tracked numeric type, so value keeps int or float
    _K = TypeVar("_K")  # tracked dict key type
    _V = TypeVar("_V")  # tracked dict value type
    _B_co = TypeVar("_B_co", bytes, bytearray, covariant=True)  # tracked bytes type (output-only -> covariant)
    _U = TypeVar("_U")  # the type a TypeIs predicate refines the tracked value to

    # what a number may be compared against: anything that can produce a float. Named as a capability
    # rather than as a list of types, because the list was wrong the first time - it said
    # `float | Decimal | Fraction` and rejected `numpy.int64`, which this library documents support for
    # and which the runtime compares happily. `str`, `complex`, `date` and containers have no
    # `__float__`, so the mistakes worth catching stay caught
    _Number = SupportsFloat

    # Predicates read `Callable[[Any], object]`, or `[Any, Any]` where the runtime hands over a pair.
    # The verdict is `object` because the runtime reads it for truth: `bool` refused a `numpy.bool_`
    # verdict, the same mistake the numeric bound made once by naming types and rejecting `numpy.int64`.
    # The arity is the runtime's: `each` and its neighbours call with one argument, `zip_satisfies` and
    # `comparators` with two, and either raises when handed the other.

    class _MembershipAssertion(Protocol):
        """ "Is every one of my elements in there" asked the same way by three different types.

        Only `is_subset_of` lives here, and the reason `contains` does not is worth keeping: a string
        declares it as `str | Matcher[str]`, while a mapping and a byte string declare it untyped.
        Lifting the untyped form into a shared base looked like removing a duplicate and was really
        widening the string: `assert_that("abc").contains(123)` stopped being an error.  A capability
        protocol may only carry a declaration that every carrier means identically.
        """

        def is_subset_of(self, *supersets: object, allow_empty: bool = ...) -> Self: ...

    class _SizedAssertion(Protocol):
        """What every value with a length can be asked, declared once instead of in four protocols.

        Not on `_CoreAssertion`, because a number has no length and offering `is_empty()` on one would be
        the false promise this whole file exists to avoid.  Not generated either: a protocol that other
        protocols inherit is the language's own way of saying "these share a capability", and a checker
        understands it without anything being generated, recorded or kept in step.
        """

        def has_same_size_as(self, other: object) -> Self: ...
        def has_size_greater_than(self, size: int) -> Self: ...
        def has_size_less_than(self, size: int) -> Self: ...
        def has_size_between(self, low: int, high: int) -> Self: ...
        def is_empty(self) -> Self: ...
        def is_not_empty(self) -> Self: ...

    class _FilesystemAssertion(Protocol):
        """What a value naming a place on disk can be asked.

        Carried by both the string and the path protocols, because a path is written as a `str` at least
        as often as it is written as a `Path`, and refusing one of the two spellings would be a rule
        that exists only in the type checker.
        """

        def exists(self) -> Self: ...
        def does_not_exist(self) -> Self: ...
        def is_file(self) -> Self: ...
        def is_directory(self) -> Self: ...
        def is_named(self, filename: str) -> Self: ...
        def is_child_of(self, parent: object) -> Self: ...
        def is_readable(self) -> Self: ...
        def is_writable(self) -> Self: ...
        def is_executable(self) -> Self: ...

    class _RealNumberAssertion(Protocol):
        """What a real number can be asked, whether it is spelled `int`, `float` or `bool`.

        `bool` is here because it is an `int` in Python, and an assertion that works on one works on the
        other; leaving it out would be a distinction the runtime does not make.
        """

        def is_positive(self) -> Self: ...
        def is_negative(self) -> Self: ...
        def is_nan(self) -> Self: ...
        def is_not_nan(self) -> Self: ...
        def is_inf(self) -> Self: ...
        def is_not_inf(self) -> Self: ...
        def is_close_to(self, other: _Number, tolerance: _Number) -> Self: ...
        def is_not_close_to(self, other: _Number, tolerance: _Number) -> Self: ...
        def is_not_between(self, low: _Number, high: _Number) -> Self: ...
        def is_between(self, low: _Number, high: _Number) -> Self: ...
        def is_greater_than(self, other: _Number) -> Self: ...
        def is_greater_than_or_equal_to(self, other: _Number) -> Self: ...
        def is_less_than(self, other: _Number) -> Self: ...
        def is_less_than_or_equal_to(self, other: _Number) -> Self: ...

    class _StructureAssertion(Protocol):
        """Quantifiers, the JSON family and the two pivots, which a mapping and a sequence share.

        That sharing is what a JSON document is made of, and the reason these never belonged to either
        one alone.  `extracting` and `at_json_path` joined them once both stopped promising the shape of
        their own subject: a path lands on whatever the document holds there, and extraction builds a
        list out of either.
        """

        # ExtractingMixin and JsonMixin: both drop the subject's own shape, so both fit here
        def extracting(
            self,
            # a selector stays `object`: whether one works depends on the row, and every narrowing
            # refused working code.  `str | int` refuses tuple, float, bytes and `None` keys;
            # `Hashable` refuses `slice(0, 2)`, unhashable before 3.12 and accepted at runtime;
            # `Hashable | slice` refuses a list key on a mapping whose `__getitem__` takes one.
            # The first selector is required: without one the runtime raises anyway
            name: object,
            *names: object,
            # named rather than `**kwargs`, because the runtime accepts exactly these two and rejects
            # anything else by name: a typo like `filtr=` should not have to wait for the run to say so
            # `Mapping` rather than `dict`, which is invariant and refuses a `dict[str, str]` variable.
            # `str` keys are a stated limit: other keys are accepted and then skipped, so a wider type
            # would describe a filter that does nothing
            filter: str | Mapping[str, object] | Callable[[Any], object] = ...,  # noqa: A002  # public keyword
            # `sort` is narrower by the runtime's own rule: a single index is refused, the same index
            # inside a list is honoured
            sort: str | Iterable[object] | Callable[[Any], object] = ...,
        ) -> _ListAssertion[Any]: ...
        def at_json_path(self, path: str) -> _CoreAssertion:
            """Navigate into the document and continue on whatever is there.

            A path lands on an object, an array, a string, a number, a boolean or a null, and which one
            it is lives in the document rather than in any type.  So what comes back offers the
            assertions every value can answer, and nothing beyond them: naming a shape here is what
            offered `contains_key` on an `int` and made a type check pass on a call that raises.

            Reaching further is a narrowing the caller states: a matcher, or a `TypeIs` predicate that
            carries the type into the rest of the chain.  What runs is the predicate, and what is read
            is its boolean answer, so the declared narrowing is taken on trust from whoever wrote it.
            """
            ...

        def each(self, matcher: Matcher[Any] | Callable[[Any], object], *, allow_empty: bool = ...) -> Self: ...
        def all_satisfy(self, matcher: Matcher[Any] | Callable[[Any], object], *, allow_empty: bool = ...) -> Self: ...
        def has_json_path(self, path: str) -> Self: ...
        def does_not_have_json_path(self, path: str) -> Self: ...
        def matches_json_schema(self, schema: dict[str, Any]) -> Self: ...
        def matches_json_schema_from_file(self, path: str | Path) -> Self: ...
        def conforms_to_openapi(
            self,
            spec: dict[str, Any],
            path: str,
            method: str,
            *,
            status: str | int | None = ...,
            content_type: str = ...,
        ) -> Self: ...

    class _RepeatableAssertion(Protocol[_E]):
        """What a value with repeatable elements can be asked about its repeats and their order.

        Generic over the element, and that is not decoration: `contains_in_order` names the element type,
        so a protocol without the parameter leaves `_E` free and lets a list of integers be asked about
        strings.  Each carrier binds it to what its own elements are.
        """

        def contains_duplicates(self) -> Self: ...
        def does_not_contain_duplicates(self) -> Self: ...
        def contains_only_once(self, *items: object) -> Self: ...
        def contains_in_order(self, *items: _E | Matcher[_E]) -> Self: ...

    class _ZeroAssertion(Protocol):
        """Zero and its negation, which every numeric spelling shares, complex included."""

        def is_zero(self) -> Self: ...
        def is_not_zero(self) -> Self: ...

    class _CoreAssertion(Protocol):
        """Base protocol with assertions available for all types."""

        # BaseMixin
        def described_as(self, description: str) -> Self: ...
        def is_equal_to(
            self,
            other: object,
            *,
            ignore: _KeySpecs | None = ...,
            include: _KeySpecs | None = ...,
            tolerance: float | None = ...,
            comparators: dict[object, Callable[[Any, Any], object]] | None = ...,
            ignore_null: bool = ...,
            strict_types: bool = ...,
        ) -> Self: ...
        def is_not_equal_to(self, other: object) -> Self: ...
        def is_same_as(self, other: object) -> Self: ...
        def is_not_same_as(self, other: object) -> Self: ...
        def is_true(self) -> Self: ...
        def is_false(self) -> Self: ...
        def is_none(self) -> Self: ...
        def is_not_none(self) -> Self: ...
        def is_type_of(self, some_type: type) -> Self: ...
        # deliberately not the narrowing overload pair the generic fallback carries.  Refining by class
        # from an already concrete type has no caller: a `dict[str, Any]` is never an instance of a
        # domain class, and the case that is real (`object` / `Any` narrowed by isinstance) resolves on
        # the fallback, where it always worked.  The pair costs two `reportOverlappingOverload` for that
        def is_instance_of(self, some_class: type) -> Self: ...
        def is_instance_of_any(self, *some_classes: type) -> Self: ...
        def is_subclass_of(self, some_class: type) -> Self: ...
        def is_length(self, length: int) -> Self: ...
        def is_length_between(self, low: int, high: int) -> Self: ...
        def is_callable(self) -> Self: ...
        def is_not_callable(self) -> Self: ...
        # CollectionMixin - a question about any value, like the callable pair above it: asking whether a
        # date or a number can be walked is a fair question with a plain answer, not a domain error.  Held
        # here rather than copied into eleven protocols, which is what having it on the collection view
        # alone amounted to
        def is_iterable(self) -> Self: ...
        def is_not_iterable(self) -> Self: ...
        # the same refinement the generic fallback offers, so a domain predicate narrows the chain
        # from a concretely typed value too, not only from the untyped one
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[_U]]) -> AssertionBuilder[_U]: ...
        @overload
        def satisfies(self, matcher: Matcher[Any] | Callable[[Any], object]) -> Self: ...
        def all_fields_satisfy(
            self, matcher: Matcher[Any] | Callable[[Any], object], *, allow_empty: bool = ...
        ) -> Self: ...
        def has_no_none_fields(self, *, allow_empty: bool = ...) -> Self: ...
        # ContainsMixin - universal
        def is_in(self, *items: object) -> Self: ...
        def is_not_in(self, *items: object) -> Self: ...
        # SnapshotMixin
        def snapshot(
            self,
            id: str | None = ...,  # noqa: A002  # mirrors public snapshot() parameter
            path: str = ...,
            *,
            ignore: _KeySpecs | None = ...,
            include: _KeySpecs | None = ...,
            tolerance: float | None = ...,
            comparators: dict[object, Callable[[Any, Any], object]] | None = ...,
            placeholders: dict[Hashable, Matcher[Any] | Callable[[Any], object]] | None = ...,
        ) -> Self: ...
        def matches_contract_snapshot(self, id: str | None = ..., path: str = ...) -> Self: ...  # noqa: A002  # mirrors public parameter
        def matches_inline(
            self,
            expected: object = ...,
            *,
            ignore: _KeySpecs | None = ...,
            include: _KeySpecs | None = ...,
            tolerance: float | None = ...,
            comparators: dict[object, Callable[[Any, Any], object]] | None = ...,
            placeholders: dict[Hashable, Matcher[Any] | Callable[[Any], object]] | None = ...,
        ) -> Self: ...
        # NegatedBuilder
        @property
        def not_(self) -> NegatedBuilder[Self]: ...
        # CheckBuilder - run the next assertion for its verdict instead of for its failure
        def check(self) -> CheckBuilder: ...
        # AssertionBuilder - typed extract-and-continue
        @property
        def value(self) -> object: ...

    class _TextAssertion(_MembershipAssertion, _RepeatableAssertion[str], _SizedAssertion, _CoreAssertion, Protocol):
        """What a piece of text can be asked, whether a caller passed it in or the library caught it.

        Split out from the string view so the invoked view can share it without sharing the rest.  The
        message a raised exception hands back is a `str`, so every assertion here applies to it, and
        the assertions that read a path do not: that inheritance offered `exists()` on the text of an
        exception, which the runtime then looks for on disk.
        """

        # narrowed from the core: the value under test is a `str`, so a matcher built for another type
        # is a type error here rather than something only the runtime discovers
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[_U]]) -> AssertionBuilder[_U]: ...
        @overload
        def satisfies(self, matcher: Matcher[str] | Callable[[Any], object]) -> Self: ...

        """Assertions available for ``str`` values."""

        def contains(self, *items: str | Matcher[str]) -> Self: ...

        @property
        def value(self) -> str: ...
        # StringMixin
        def is_equal_to_ignoring_case(self, other: str) -> Self: ...
        def is_equal_to_ignoring_whitespace(self, other: str) -> Self: ...
        def contains_ignoring_case(self, *items: str) -> Self: ...
        def starts_with(self, prefix: str) -> Self: ...
        def starts_with_ignoring_case(self, prefix: str) -> Self: ...
        def ends_with(self, suffix: str) -> Self: ...
        def ends_with_ignoring_case(self, suffix: str) -> Self: ...
        def matches(self, pattern: str) -> Self: ...
        def does_not_match(self, pattern: str) -> Self: ...
        def is_alpha(self) -> Self: ...
        def is_digit(self) -> Self: ...
        def is_lower(self) -> Self: ...
        def is_upper(self) -> Self: ...
        def is_alphanumeric(self) -> Self: ...
        def is_whitespace(self) -> Self: ...
        def contains_any_of(self, *items: str) -> Self: ...
        def contains_none_of(self, *items: str) -> Self: ...
        def is_unicode(self) -> Self: ...
        # NumericMixin - lexicographic ordering
        def is_greater_than(self, other: str) -> Self: ...
        def is_greater_than_or_equal_to(self, other: str) -> Self: ...
        def is_less_than(self, other: str) -> Self: ...
        def is_less_than_or_equal_to(self, other: str) -> Self: ...
        # ContainsMixin, bound to `str`: every one of these takes a substring, and a matcher stands in
        # for one wherever a substring is accepted
        def does_not_contain(self, *items: str | Matcher[str]) -> Self: ...
        def contains_only(self, *items: str | Matcher[str]) -> Self: ...
        def contains_sequence(self, *items: str | Matcher[str]) -> Self: ...
        def contains_exactly(self, *items: str | Matcher[str]) -> Self: ...
        def contains_exactly_in_any_order(self, *items: str | Matcher[str]) -> Self: ...
        # a string is walked character by character, so the key sees a one-character `str`
        def is_sorted(
            self, key: Callable[[str], object] = ..., reverse: bool = ..., *, allow_empty: bool = ...
        ) -> Self: ...
        # CollectionMixin - pipeline.  A character of a string is a string, so the element pivots stay on
        # this protocol instead of widening to the generic builder, which would hand a one-character
        # value the whole API back
        def filtered_on(self, predicate: Matcher[str] | Callable[[str], object]) -> _ListAssertion[str]: ...
        def mapped(self, func: Callable[[str], _R]) -> _ListAssertion[_R]: ...
        def flat_mapped(self, func: Callable[[str], Iterable[_R]]) -> _ListAssertion[_R]: ...
        # a character of a text is text, and nothing more: returning the string view here handed the
        # filesystem assertions back to a message through `.first()`, which is the promise the split
        # removed one step earlier
        def first(self) -> _TextAssertion: ...
        def last(self) -> _TextAssertion: ...
        def element(self, index: int) -> _TextAssertion: ...
        def single(self) -> _TextAssertion: ...
        # StringMixin - regex
        def extracting_group(self, pattern: str, group: int | str = ...) -> Self: ...
        # a tuple for positional groups, a dict for named ones: which cannot be known from the pattern
        # statically, so the chain continues on the untyped builder rather than pretending it is a str
        def matches_with_groups(self, pattern: str) -> AssertionBuilder[Any]: ...

    class _StringAssertion(_TextAssertion, _FilesystemAssertion, Protocol):
        """Assertions available for ``str`` values.

        The text assertions plus the ones that read the value as a path, because a path is written as a
        `str` at least as often as it is written as a `Path`.
        """

        # the pivots are redeclared to keep their result a `str` rather than the text capability: a
        # character of a string is a string, and a caller who had a path has one afterwards.  The
        # inherited form returns text, which is what a caught message needs and what keeps `exists()`
        # away from it
        def first(self) -> _StringAssertion: ...
        def last(self) -> _StringAssertion: ...
        def element(self, index: int) -> _StringAssertion: ...
        def single(self) -> _StringAssertion: ...

        # FileMixin

    class _NumericAssertion(_RealNumberAssertion, _ZeroAssertion, _CoreAssertion, Protocol[_N]):
        """Assertions available for ``int`` and ``float`` values.

        Generic over the number type ``_N`` so ``value`` keeps the exact numeric type instead of the
        ``int | float`` union.

        `complex` and `bool` have protocols of their own, each carrying what the runtime actually
        accepts for that type rather than the whole numeric set.
        """

        @property
        def value(self) -> _N: ...
        # narrowed from the core, for the same reason the string protocol narrows it
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[_U]]) -> AssertionBuilder[_U]: ...
        @overload
        def satisfies(self, matcher: Matcher[_N] | Callable[[Any], object]) -> Self: ...
        # `_Number` rather than `_N`: comparing an `int` against a `float` is ordinary and has to keep
        # working, while comparing either against text is the mistake worth catching. `Decimal` and
        # `Fraction` are named because the stdlib's own numbers do not form a static hierarchy
        def is_even(self) -> Self: ...
        def is_odd(self) -> Self: ...
        def is_divisible_by(self, divisor: int) -> Self: ...

    class _ComplexAssertion(_ZeroAssertion, _CoreAssertion, Protocol):
        """Assertions available for ``complex`` values, which is far fewer than for a real number.

        Ordering is not defined for a complex number, and neither is parity, divisibility, NaN or
        infinity: the runtime refuses all thirteen of those with `TypeError: ordering is not defined for
        type <complex>` and its relatives.  It used to advertise them anyway, because `complex` shared
        the numeric protocol, so a checker suggested a method whose only outcome was a crash.
        """

        @property
        def value(self) -> complex: ...

    class _BoolAssertion(_RealNumberAssertion, _ZeroAssertion, _CoreAssertion, Protocol):
        """Assertions available for ``bool``, which is every numeric one except the integer-only three.

        `bool` is a subclass of `int`, so it used to resolve to the numeric protocol and be offered
        `is_even`, `is_odd` and `is_divisible_by`.  The runtime refuses exactly those three with
        `TypeError: val is not an integer, got bool`, and accepts the rest: `True > 0` is a real
        comparison.  The type now says the same thing.
        """

        @property
        def value(self) -> bool: ...

    class _IterableAssertion(
        _StructureAssertion, _RepeatableAssertion[_E], _SizedAssertion, _CoreAssertion, Protocol[_E]
    ):
        """Assertions available for ``list``, ``tuple``, ``set``, and ``frozenset`` values.

        Generic over the element type ``_E`` so element-access pivots (``first``/``last``/``element``/
        ``single``) narrow the chain to the element, and ``value`` keeps the element type.
        """

        @property
        def value(self) -> list[_E] | tuple[_E, ...] | set[_E] | frozenset[_E]: ...
        # ContainsMixin, bound to the element type: an item of another type can never be in there, and
        # a matcher stands in for an item wherever one is accepted
        def contains(self, *items: _E | Matcher[_E]) -> Self: ...
        def does_not_contain(self, *items: _E | Matcher[_E]) -> Self: ...
        def contains_only(self, *items: _E | Matcher[_E]) -> Self: ...
        def contains_sequence(self, *items: _E | Matcher[_E]) -> Self: ...
        def contains_exactly(self, *items: _E | Matcher[_E]) -> Self: ...
        def contains_exactly_in_any_order(self, *items: _E | Matcher[_E]) -> Self: ...
        # CollectionMixin - the iterable pair lives on the core protocol, where every value can ask it
        def is_subset_of(self, *supersets: Iterable[_E], allow_empty: bool = ...) -> Self: ...
        def is_sorted(
            self, key: Callable[[_E], object] = ..., reverse: bool = ..., *, allow_empty: bool = ...
        ) -> Self: ...
        # StringMixin - both work on any ordered sequence, not just str, and the docs show them on lists
        def starts_with(self, prefix: _E) -> Self: ...
        def ends_with(self, suffix: _E) -> Self: ...
        # BaseMixin
        # narrowed from the structure capability, which cannot know the element: here it is _E
        def each(self, matcher: Matcher[_E] | Callable[[_E], object], *, allow_empty: bool = ...) -> Self: ...
        def all_satisfy(self, matcher: Matcher[_E] | Callable[[_E], object], *, allow_empty: bool = ...) -> Self: ...
        def any_satisfy(self, matcher: Matcher[_E] | Callable[[_E], object]) -> Self: ...
        def none_satisfy(self, matcher: Matcher[_E] | Callable[[_E], object]) -> Self: ...
        def satisfies_exactly(self, *matchers: Matcher[_E] | Callable[[_E], object]) -> Self: ...
        def satisfies_exactly_in_any_order(self, *matchers: Matcher[_E] | Callable[[_E], object]) -> Self: ...
        def zip_satisfies(
            self, other: Iterable[object], predicate: Callable[[Any, Any], object], *, allow_empty: bool = ...
        ) -> Self: ...
        # CollectionMixin - pipeline (filter keeps the element type; map changes it; access yields the element)
        def filtered_on(self, predicate: Matcher[_E] | Callable[[_E], object]) -> _ListAssertion[_E]: ...
        def mapped(self, func: Callable[[_E], _R]) -> _ListAssertion[_R]: ...
        def flat_mapped(self, func: Callable[[_E], Iterable[_R]]) -> _ListAssertion[_R]: ...
        def first(self) -> AssertionBuilder[_E]: ...
        def last(self) -> AssertionBuilder[_E]: ...
        def element(self, index: int) -> AssertionBuilder[_E]: ...
        def single(self) -> AssertionBuilder[_E]: ...

    class _ListAssertion(_IterableAssertion[_E], Protocol[_E]):
        """The iterable view of a collection this library built, rather than one a caller passed in.

        Every pipeline step returns one of these, and the difference from `_IterableAssertion` is a single
        line: `value` is a `list`, not one of four containers.  That is not a guess.  `filtered_on`,
        `mapped`, `flat_mapped` and `extracting` build a list whatever they were given, on a `tuple`, a
        `set` and a `frozenset` alike, so declaring the union afterwards described an input that has
        already been left behind, and made callers narrow a type the library had already settled.
        """

        @property
        def value(self) -> list[_E]: ...

    class _DictAssertion(_MembershipAssertion, _StructureAssertion, _SizedAssertion, _CoreAssertion, Protocol[_K, _V]):
        """Assertions available for ``dict`` values, generic over the key and value types."""

        def contains(self, *items: object) -> Self: ...

        @property
        def value(self) -> dict[_K, _V]: ...
        # DictMixin
        # narrowed from the structure capability, which cannot know the element: here it is _K
        def each(self, matcher: Matcher[_K] | Callable[[_K], object], *, allow_empty: bool = ...) -> Self: ...
        def all_satisfy(self, matcher: Matcher[_K] | Callable[[_K], object], *, allow_empty: bool = ...) -> Self: ...
        def contains_key(self, *keys: _K | Matcher[_K]) -> Self: ...
        def does_not_contain_key(self, *keys: _K | Matcher[_K]) -> Self: ...
        def contains_value(self, *values: _V | Matcher[_V]) -> Self: ...
        def does_not_contain_value(self, *values: _V | Matcher[_V]) -> Self: ...
        def contains_entry(self, *args: object, **kwargs: object) -> Self: ...
        def does_not_contain_entry(self, *args: object, **kwargs: object) -> Self: ...
        # ContainsMixin
        def does_not_contain(self, *items: object) -> Self: ...
        def contains_only(self, *keys: object) -> Self: ...
        # CollectionMixin - a dict is compared against other dicts, key by key
        # iterating a dict yields its keys, so that is what the sort key is handed
        def is_sorted(
            self, key: Callable[[_K], object] = ..., reverse: bool = ..., *, allow_empty: bool = ...
        ) -> Self: ...
        # CollectionMixin - pipeline over the keys.  The element pivots hand back the generic builder
        # rather than a narrowed view: a key is of an arbitrary type `_K`, and turning an arbitrary type
        # into the protocol `assert_that` would pick for it is the type-level dispatch this API lacks
        def filtered_on(self, predicate: Matcher[_K] | Callable[[_K], object]) -> _ListAssertion[_K]: ...
        def mapped(self, func: Callable[[_K], _R]) -> _ListAssertion[_R]: ...
        def flat_mapped(self, func: Callable[[_K], Iterable[_R]]) -> _ListAssertion[_R]: ...
        def first(self) -> AssertionBuilder[_K]: ...
        def last(self) -> AssertionBuilder[_K]: ...
        def element(self, index: int) -> AssertionBuilder[_K]: ...
        def single(self) -> AssertionBuilder[_K]: ...
        # BaseMixin
        def matches_structure(self, spec: dict) -> Self: ...

        # the same quantifier under its other name, which delegates here.  Declared alongside rather
        # than only on the sequence view: a delegate reachable in fewer places than what it delegates
        # to is a difference the runtime does not have

    class _DateAssertion(_CoreAssertion, Protocol):
        """Assertions available for ``datetime.date`` and ``datetime.datetime`` values."""

        @property
        def value(self) -> datetime.date: ...
        # a date orders against a date, and `datetime` is a `date`, so one annotation covers both
        def is_before(self, other: datetime.date) -> Self: ...
        def is_after(self, other: datetime.date) -> Self: ...
        def is_before_or_equal_to(self, other: datetime.date) -> Self: ...
        def is_after_or_equal_to(self, other: datetime.date) -> Self: ...
        def is_equal_to_ignoring_milliseconds(self, other: object) -> Self: ...
        def is_equal_to_ignoring_seconds(self, other: object) -> Self: ...
        def is_equal_to_ignoring_time(self, other: object) -> Self: ...
        # NumericMixin - chronological ordering; at runtime operands must match val's exact type
        def is_greater_than(self, other: datetime.date) -> Self: ...
        def is_greater_than_or_equal_to(self, other: datetime.date) -> Self: ...
        def is_less_than(self, other: datetime.date) -> Self: ...
        def is_less_than_or_equal_to(self, other: datetime.date) -> Self: ...
        def is_between(self, low: datetime.date, high: datetime.date) -> Self: ...

    class _PathAssertion(_FilesystemAssertion, _CoreAssertion, Protocol):
        """Assertions available for ``pathlib.Path`` values."""

        @property
        def value(self) -> Path: ...

    class _BytesAssertion(_MembershipAssertion, _SizedAssertion, _CoreAssertion, Protocol[_B_co]):
        """Assertions available for ``bytes`` and ``bytearray`` values, generic over which one."""

        def contains(self, *items: object) -> Self: ...

        @property
        def value(self) -> _B_co: ...
        # ContainsMixin
        # CollectionMixin - walking a byte string yields ints, which is what all of these see
        def is_sorted(
            self, key: Callable[[int], object] = ..., reverse: bool = ..., *, allow_empty: bool = ...
        ) -> Self: ...
        def filtered_on(self, predicate: Matcher[int] | Callable[[int], object]) -> _ListAssertion[int]: ...
        def mapped(self, func: Callable[[int], _R]) -> _ListAssertion[_R]: ...
        def flat_mapped(self, func: Callable[[int], Iterable[_R]]) -> _ListAssertion[_R]: ...
        def first(self) -> _NumericAssertion[int]: ...
        def last(self) -> _NumericAssertion[int]: ...
        def element(self, index: int) -> _NumericAssertion[int]: ...
        def single(self) -> _NumericAssertion[int]: ...
        # StringMixin - the prefix/suffix pair handles bytes natively, so a byte string reaches them
        # under their general names as well as under the bytes-only ones below
        def starts_with(self, prefix: bytes | bytearray) -> Self: ...
        def ends_with(self, suffix: bytes | bytearray) -> Self: ...
        # BytesMixin
        def is_valid_utf8(self) -> Self: ...
        def is_valid_encoding(self, encoding: str) -> Self: ...
        def starts_with_bytes(self, prefix: bytes) -> Self: ...
        def contains_bytes(self, sub: bytes) -> Self: ...
        def has_byte_at(self, index: int, expected: int) -> Self: ...
        def is_hex_equal_to(self, expected_hex: str) -> Self: ...
        def decoded_as(self, encoding: str = ...) -> _StringAssertion: ...
        # NumericMixin - lexicographic ordering
        def is_greater_than(self, other: bytes | bytearray) -> Self: ...
        def is_greater_than_or_equal_to(self, other: bytes | bytearray) -> Self: ...
        def is_less_than(self, other: bytes | bytearray) -> Self: ...
        def is_less_than_or_equal_to(self, other: bytes | bytearray) -> Self: ...

    class _InvokedAssertion(_TextAssertion, Protocol):
        """Assertions available after ``when_called_with()`` captured an exception/warning message.

        The captured message is a ``str`` (hence the text assertions, though not the ones reading a
        path: a message is not a filename);
        [`returned()`][assertpy2.exception.ExceptionMixin.returned] pivots to the value the callable
        returned.  Its static type is unknown, so ``returned()`` exposes the
        type-agnostic core assertions (``is_equal_to``, ``is_instance_of``, ``satisfies``, ...) -
        type-safe by construction, never advertising methods that may not apply.
        """

        def returned(self) -> _CoreAssertion: ...
        # raised() pivots to the caught exception object (type-agnostic, like returned());
        # caused_by()/has_root_cause() walk the cause chain and pivot to that cause's message;
        # contains_error() asserts on a caught ExceptionGroup and keeps the chain on it
        def raised(self) -> _CoreAssertion: ...
        def caused_by(self, ex: type) -> Self: ...
        def has_root_cause(self, ex: type) -> Self: ...
        def contains_error(self, *ex_types: type) -> Self: ...

    class _CallableAssertion(_CoreAssertion, Protocol):
        """Assertions available for callable values."""

        @property
        def value(self) -> Callable[..., object]: ...
        def raises(self, ex: type) -> Self: ...
        def does_not_raise(self, ex: type) -> Self: ...
        def warns(self, warning: type[Warning] = ...) -> Self: ...
        def does_not_warn(self, warning: type[Warning] = ...) -> Self: ...
        # captured value (exception or warning message) is a str; returned() pivots to the call result
        def when_called_with(self, *some_args: object, **some_kwargs: object) -> _InvokedAssertion: ...
        def eventually(
            self,
            *,
            timeout: float = ...,
            interval: float = ...,
            ignoring: type[Exception] | tuple[type[Exception], ...] = ...,
            trace: bool = ...,
        ) -> AsyncAssertionBuilder: ...
        def eventually_sync(
            self,
            *,
            timeout: float = ...,
            interval: float = ...,
            ignoring: type[Exception] | tuple[type[Exception], ...] = ...,
            trace: bool = ...,
        ) -> SyncAssertionBuilder: ...
