from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import datetime
    from collections.abc import Callable, Hashable, Iterable
    from pathlib import Path
    from typing import Any, Protocol, TypeVar

    from ._compat import Self
    from .assertpy import AssertionBuilder, NegatedBuilder
    from .async_assertions import AsyncAssertionBuilder, SyncAssertionBuilder
    from .matchers import Matcher

    # ``ignore``/``include`` accept a single key, a nested-path tuple, or a list/set/frozenset of them.
    _KeySpecs = Hashable | list[Hashable] | set[Hashable] | frozenset[Hashable]

    _E = TypeVar("_E")  # tracked element type of a collection assertion
    _R = TypeVar("_R")  # result element type after a mapping pivot
    _N = TypeVar("_N", int, float, complex)  # tracked numeric type, so value keeps int/float/complex
    _K = TypeVar("_K")  # tracked dict key type
    _V = TypeVar("_V")  # tracked dict value type
    _B_co = TypeVar("_B_co", bytes, bytearray, covariant=True)  # tracked bytes type (output-only -> covariant)

    class _CoreAssertion(Protocol):
        """Base protocol with assertions available for all types."""

        # BaseMixin
        def described_as(self, description: str) -> Self: ...
        def is_equal_to(
            self,
            other: object,
            *,
            ignore: _KeySpecs | None = ...,
            include: _KeySpecs | None = ...,
            tolerance: float | None = ...,
            comparators: dict[object, Callable[..., bool]] | None = ...,
        ) -> Self: ...
        def is_not_equal_to(self, other: object) -> Self: ...
        def is_same_as(self, other: object) -> Self: ...
        def is_not_same_as(self, other: object) -> Self: ...
        def is_true(self) -> Self: ...
        def is_false(self) -> Self: ...
        def is_none(self) -> Self: ...
        def is_not_none(self) -> Self: ...
        def is_type_of(self, some_type: type) -> Self: ...
        def is_instance_of(self, some_class: type) -> Self: ...
        def is_instance_of_any(self, *some_classes: type) -> Self: ...
        def is_subclass_of(self, some_class: type) -> Self: ...
        def is_length(self, length: int) -> Self: ...
        def is_length_between(self, low: int, high: int) -> Self: ...
        def is_callable(self) -> Self: ...
        def is_not_callable(self) -> Self: ...
        def satisfies(self, matcher: Matcher | Callable[..., bool]) -> Self: ...
        def all_fields_satisfy(self, matcher: Matcher | Callable[..., bool]) -> Self: ...
        def has_no_none_fields(self) -> Self: ...
        # ContainsMixin - universal
        def is_in(self, *items: object) -> Self: ...
        def is_not_in(self, *items: object) -> Self: ...
        # SnapshotMixin
        def snapshot(
            self,
            id: str | None = ...,  # noqa: A002  # mirrors public snapshot() parameter
            path: str = ...,
            *,
            ignore: _KeySpecs | None = ...,
            include: _KeySpecs | None = ...,
            tolerance: float | None = ...,
            comparators: dict[object, Callable[..., bool]] | None = ...,
            placeholders: dict[Hashable, Matcher | Callable[..., bool]] | None = ...,
        ) -> Self: ...
        def matches_contract_snapshot(self, id: str | None = ..., path: str = ...) -> Self: ...  # noqa: A002  # mirrors public parameter
        # NegatedBuilder
        @property
        def not_(self) -> NegatedBuilder: ...
        # AssertionBuilder - typed extract-and-continue
        @property
        def value(self) -> object: ...

    class _StringAssertion(_CoreAssertion, Protocol):
        """Assertions available for ``str`` values."""

        @property
        def value(self) -> str: ...
        # StringMixin
        def is_equal_to_ignoring_case(self, other: str) -> Self: ...
        def is_equal_to_ignoring_whitespace(self, other: str) -> Self: ...
        def contains_ignoring_case(self, *items: str) -> Self: ...
        def starts_with(self, prefix: str) -> Self: ...
        def starts_with_ignoring_case(self, prefix: str) -> Self: ...
        def ends_with(self, suffix: str) -> Self: ...
        def ends_with_ignoring_case(self, suffix: str) -> Self: ...
        def matches(self, pattern: str) -> Self: ...
        def does_not_match(self, pattern: str) -> Self: ...
        def is_alpha(self) -> Self: ...
        def is_digit(self) -> Self: ...
        def is_lower(self) -> Self: ...
        def is_upper(self) -> Self: ...
        def is_alphanumeric(self) -> Self: ...
        def is_whitespace(self) -> Self: ...
        def contains_any_of(self, *items: str) -> Self: ...
        def contains_none_of(self, *items: str) -> Self: ...
        def is_unicode(self) -> Self: ...
        # NumericMixin - lexicographic ordering
        def is_greater_than(self, other: str) -> Self: ...
        def is_greater_than_or_equal_to(self, other: str) -> Self: ...
        def is_less_than(self, other: str) -> Self: ...
        def is_less_than_or_equal_to(self, other: str) -> Self: ...
        # ContainsMixin
        def contains(self, *items: object) -> Self: ...
        def does_not_contain(self, *items: object) -> Self: ...
        def contains_only(self, *items: object) -> Self: ...
        def contains_sequence(self, *items: object) -> Self: ...
        def contains_duplicates(self) -> Self: ...
        def does_not_contain_duplicates(self) -> Self: ...
        def contains_exactly(self, *items: object) -> Self: ...
        def contains_exactly_in_any_order(self, *items: object) -> Self: ...
        def contains_in_order(self, *items: object) -> Self: ...
        def contains_only_once(self, *items: object) -> Self: ...
        def has_same_size_as(self, other: object) -> Self: ...
        def has_size_greater_than(self, size: int) -> Self: ...
        def has_size_less_than(self, size: int) -> Self: ...
        def has_size_between(self, low: int, high: int) -> Self: ...
        def is_empty(self) -> Self: ...
        def is_not_empty(self) -> Self: ...
        def is_subset_of(self, *supersets: object) -> Self: ...
        # StringMixin - regex
        def extracting_group(self, pattern: str, group: int | str = ...) -> Self: ...
        def matches_with_groups(self, pattern: str) -> Self: ...
        # FileMixin
        def exists(self) -> Self: ...
        def does_not_exist(self) -> Self: ...
        def is_file(self) -> Self: ...
        def is_directory(self) -> Self: ...
        def is_named(self, filename: str) -> Self: ...
        def is_child_of(self, parent: object) -> Self: ...
        def is_readable(self) -> Self: ...
        def is_writable(self) -> Self: ...
        def is_executable(self) -> Self: ...

    class _NumericAssertion(_CoreAssertion, Protocol[_N]):
        """Assertions available for ``int``, ``float``, and ``complex`` values.

        Generic over the number type ``_N`` so ``value`` keeps the exact numeric type instead of the
        ``int | float | complex`` union.
        """

        @property
        def value(self) -> _N: ...
        def is_zero(self) -> Self: ...
        def is_not_zero(self) -> Self: ...
        def is_nan(self) -> Self: ...
        def is_not_nan(self) -> Self: ...
        def is_inf(self) -> Self: ...
        def is_not_inf(self) -> Self: ...
        def is_greater_than(self, other: object) -> Self: ...
        def is_greater_than_or_equal_to(self, other: object) -> Self: ...
        def is_less_than(self, other: object) -> Self: ...
        def is_less_than_or_equal_to(self, other: object) -> Self: ...
        def is_positive(self) -> Self: ...
        def is_negative(self) -> Self: ...
        def is_even(self) -> Self: ...
        def is_odd(self) -> Self: ...
        def is_divisible_by(self, divisor: int) -> Self: ...
        def is_between(self, low: object, high: object) -> Self: ...
        def is_not_between(self, low: object, high: object) -> Self: ...
        def is_close_to(self, other: object, tolerance: object) -> Self: ...
        def is_not_close_to(self, other: object, tolerance: object) -> Self: ...

    class _IterableAssertion(_CoreAssertion, Protocol[_E]):
        """Assertions available for ``list``, ``tuple``, ``set``, and ``frozenset`` values.

        Generic over the element type ``_E`` so element-access pivots (``first``/``last``/``element``/
        ``single``) narrow the chain to the element, and ``value`` keeps the element type.
        """

        @property
        def value(self) -> list[_E] | tuple[_E, ...] | set[_E] | frozenset[_E]: ...
        # ContainsMixin
        def contains(self, *items: object) -> Self: ...
        def does_not_contain(self, *items: object) -> Self: ...
        def contains_only(self, *items: object) -> Self: ...
        def contains_sequence(self, *items: object) -> Self: ...
        def contains_duplicates(self) -> Self: ...
        def does_not_contain_duplicates(self) -> Self: ...
        def contains_exactly(self, *items: object) -> Self: ...
        def contains_exactly_in_any_order(self, *items: object) -> Self: ...
        def contains_in_order(self, *items: object) -> Self: ...
        def is_empty(self) -> Self: ...
        def is_not_empty(self) -> Self: ...
        # CollectionMixin
        def is_iterable(self) -> Self: ...
        def is_not_iterable(self) -> Self: ...
        def is_subset_of(self, *supersets: object) -> Self: ...
        def is_sorted(self, key: Callable[..., object] = ..., reverse: bool = ...) -> Self: ...
        # ExtractingMixin - extracted values have a dynamic type, so the element type is dropped
        def extracting(self, *names: object, **kwargs: object) -> _IterableAssertion[Any]: ...
        # BaseMixin
        def each(self, matcher: Matcher | Callable[..., bool]) -> Self: ...
        def any_satisfy(self, matcher: Matcher | Callable[..., bool]) -> Self: ...
        def all_satisfy(self, matcher: Matcher | Callable[..., bool]) -> Self: ...
        def none_satisfy(self, matcher: Matcher | Callable[..., bool]) -> Self: ...
        def satisfies_exactly(self, *matchers: Matcher | Callable[..., bool]) -> Self: ...
        def satisfies_exactly_in_any_order(self, *matchers: Matcher | Callable[..., bool]) -> Self: ...
        def zip_satisfies(self, other: Iterable[object], predicate: Callable[..., bool]) -> Self: ...
        def contains_only_once(self, *items: object) -> Self: ...
        def has_same_size_as(self, other: object) -> Self: ...
        def has_size_greater_than(self, size: int) -> Self: ...
        def has_size_less_than(self, size: int) -> Self: ...
        def has_size_between(self, low: int, high: int) -> Self: ...
        # CollectionMixin - pipeline (filter keeps the element type; map changes it; access yields the element)
        def filtered_on(self, predicate: Callable[..., bool]) -> Self: ...
        def mapped(self, func: Callable[[_E], _R]) -> _IterableAssertion[_R]: ...
        def flat_mapped(self, func: Callable[[_E], Iterable[_R]]) -> _IterableAssertion[_R]: ...
        def first(self) -> AssertionBuilder[_E]: ...
        def last(self) -> AssertionBuilder[_E]: ...
        def element(self, index: int) -> AssertionBuilder[_E]: ...
        def single(self) -> AssertionBuilder[_E]: ...
        # JsonMixin - navigation yields a dynamically-typed value, so the element type is dropped
        def at_json_path(self, path: str) -> _IterableAssertion[Any]: ...
        def has_json_path(self, path: str) -> Self: ...
        def does_not_have_json_path(self, path: str) -> Self: ...
        def matches_json_schema(self, schema: dict[str, Any]) -> Self: ...
        def matches_json_schema_from_file(self, path: str | Path) -> Self: ...

    class _DictAssertion(_CoreAssertion, Protocol[_K, _V]):
        """Assertions available for ``dict`` values, generic over the key and value types."""

        @property
        def value(self) -> dict[_K, _V]: ...
        # DictMixin
        def contains_key(self, *keys: object) -> Self: ...
        def does_not_contain_key(self, *keys: object) -> Self: ...
        def contains_value(self, *values: object) -> Self: ...
        def does_not_contain_value(self, *values: object) -> Self: ...
        def contains_entry(self, *args: object, **kwargs: object) -> Self: ...
        def does_not_contain_entry(self, *args: object, **kwargs: object) -> Self: ...
        # ContainsMixin
        def contains(self, *items: object) -> Self: ...
        def does_not_contain(self, *items: object) -> Self: ...
        def has_same_size_as(self, other: object) -> Self: ...
        def has_size_greater_than(self, size: int) -> Self: ...
        def has_size_less_than(self, size: int) -> Self: ...
        def has_size_between(self, low: int, high: int) -> Self: ...
        def is_empty(self) -> Self: ...
        def is_not_empty(self) -> Self: ...
        # BaseMixin
        def matches_structure(self, spec: dict) -> Self: ...
        def each(self, matcher: Matcher | Callable[..., bool]) -> Self: ...
        # ExtractingMixin - extracted values have a dynamic type, so the key/value types are dropped
        def extracting(self, *names: object, **kwargs: object) -> _DictAssertion[Any, Any]: ...
        # JsonMixin - navigation yields a dynamically-typed value, so the key/value types are dropped
        def at_json_path(self, path: str) -> _DictAssertion[Any, Any]: ...
        def has_json_path(self, path: str) -> Self: ...
        def does_not_have_json_path(self, path: str) -> Self: ...
        def matches_json_schema(self, schema: dict[str, Any]) -> Self: ...
        def matches_json_schema_from_file(self, path: str | Path) -> Self: ...

    class _DateAssertion(_CoreAssertion, Protocol):
        """Assertions available for ``datetime.date`` and ``datetime.datetime`` values."""

        @property
        def value(self) -> datetime.date: ...
        def is_before(self, other: object) -> Self: ...
        def is_after(self, other: object) -> Self: ...
        def is_before_or_equal_to(self, other: object) -> Self: ...
        def is_after_or_equal_to(self, other: object) -> Self: ...
        def is_equal_to_ignoring_milliseconds(self, other: object) -> Self: ...
        def is_equal_to_ignoring_seconds(self, other: object) -> Self: ...
        def is_equal_to_ignoring_time(self, other: object) -> Self: ...
        # NumericMixin - chronological ordering; at runtime operands must match val's exact type
        def is_greater_than(self, other: datetime.date) -> Self: ...
        def is_greater_than_or_equal_to(self, other: datetime.date) -> Self: ...
        def is_less_than(self, other: datetime.date) -> Self: ...
        def is_less_than_or_equal_to(self, other: datetime.date) -> Self: ...
        def is_between(self, low: datetime.date, high: datetime.date) -> Self: ...

    class _PathAssertion(_CoreAssertion, Protocol):
        """Assertions available for ``pathlib.Path`` values."""

        @property
        def value(self) -> Path: ...
        def exists(self) -> Self: ...
        def does_not_exist(self) -> Self: ...
        def is_file(self) -> Self: ...
        def is_directory(self) -> Self: ...
        def is_named(self, filename: str) -> Self: ...
        def is_child_of(self, parent: object) -> Self: ...
        def is_readable(self) -> Self: ...
        def is_writable(self) -> Self: ...
        def is_executable(self) -> Self: ...

    class _BytesAssertion(_CoreAssertion, Protocol[_B_co]):
        """Assertions available for ``bytes`` and ``bytearray`` values, generic over which one."""

        @property
        def value(self) -> _B_co: ...
        # ContainsMixin
        def contains(self, *items: object) -> Self: ...
        def has_same_size_as(self, other: object) -> Self: ...
        def has_size_greater_than(self, size: int) -> Self: ...
        def has_size_less_than(self, size: int) -> Self: ...
        def has_size_between(self, low: int, high: int) -> Self: ...
        def is_empty(self) -> Self: ...
        def is_not_empty(self) -> Self: ...
        # BytesMixin
        def is_valid_utf8(self) -> Self: ...
        def is_valid_encoding(self, encoding: str) -> Self: ...
        def starts_with_bytes(self, prefix: bytes) -> Self: ...
        def contains_bytes(self, sub: bytes) -> Self: ...
        def has_byte_at(self, index: int, expected: int) -> Self: ...
        def is_hex_equal_to(self, expected_hex: str) -> Self: ...
        def decoded_as(self, encoding: str = ...) -> _StringAssertion: ...
        # NumericMixin - lexicographic ordering
        def is_greater_than(self, other: bytes | bytearray) -> Self: ...
        def is_greater_than_or_equal_to(self, other: bytes | bytearray) -> Self: ...
        def is_less_than(self, other: bytes | bytearray) -> Self: ...
        def is_less_than_or_equal_to(self, other: bytes | bytearray) -> Self: ...

    class _InvokedAssertion(_StringAssertion, Protocol):
        """Assertions available after ``when_called_with()`` captured an exception/warning message.

        The captured message is a ``str`` (hence the string assertions);
        [`returned()`][assertpy2.exception.ExceptionMixin.returned] pivots to the value the callable
        returned.  Its static type is unknown, so ``returned()`` exposes the
        type-agnostic core assertions (``is_equal_to``, ``is_instance_of``, ``satisfies``, ...) -
        type-safe by construction, never advertising methods that may not apply.
        """

        def returned(self) -> _CoreAssertion: ...
        # raised() pivots to the caught exception object (type-agnostic, like returned());
        # caused_by()/has_root_cause() walk the cause chain and pivot to that cause's message;
        # contains_error() asserts on a caught ExceptionGroup and keeps the chain on it
        def raised(self) -> _CoreAssertion: ...
        def caused_by(self, ex: type) -> Self: ...
        def has_root_cause(self, ex: type) -> Self: ...
        def contains_error(self, *ex_types: type) -> Self: ...

    class _CallableAssertion(_CoreAssertion, Protocol):
        """Assertions available for callable values."""

        @property
        def value(self) -> Callable[..., object]: ...
        def raises(self, ex: type) -> Self: ...
        def does_not_raise(self, ex: type) -> Self: ...
        def warns(self, warning: type[Warning] = ...) -> Self: ...
        def does_not_warn(self, warning: type[Warning] = ...) -> Self: ...
        # captured value (exception or warning message) is a str; returned() pivots to the call result
        def when_called_with(self, *some_args: object, **some_kwargs: object) -> _InvokedAssertion: ...
        def eventually(
            self,
            *,
            timeout: float = ...,
            interval: float = ...,
            ignoring: type[Exception] | tuple[type[Exception], ...] = ...,
            trace: bool = ...,
        ) -> AsyncAssertionBuilder: ...
        def eventually_sync(
            self,
            *,
            timeout: float = ...,
            interval: float = ...,
            ignoring: type[Exception] | tuple[type[Exception], ...] = ...,
            trace: bool = ...,
        ) -> SyncAssertionBuilder: ...
