"""Generate the polling twins of the assertion protocols.

A polling chain records the assertion and replays it until it holds, so every assertion is available
through it with the return type replaced by the chain itself.  Both builders resolve the name at run
time through `__getattr__`, which no checker can read: until this existed, a polling chain was `Any`
from the first assertion onwards, and `eventually_sync().method_that_does_not_exist()` passed all
three checkers.

The twins are one flat protocol per flavour rather than one per view, and each assertion carries the
value types it applies to in its own ``self`` annotation.  A view per value type would have to be
chosen by `eventually_sync()`, whose overloads see the probe's return type: measured, a probe with no
annotation returns `Any`, an `Any` self matches the first rung, and every checker then reported a
string assertion on a chain that polls anything.  Per-assertion ``self`` inverts that: an `Any` chain
matches every rung and keeps the freedom it has today, and an annotated one is held to its type.

Two more shapes were measured against the same pair of questions, and both fail on the second one.  The
questions: does a string chain refuse `is_positive()`, and does an unannotated probe keep
`has_status("PAID")`.

* **a view per value type.**  The assertion is not declared on the view at all, so `__getattr__` answers
  it and nothing is refused.  Taking the hook off does refuse it on all three, and then mypy refuses
  `has_status("PAID")` on an unannotated probe, which is the idiom the hook exists for.
* **a view per value type, hook kept, with the assertions a view does not carry declared as
  non-callable sentinels** so a declaration shadows the hook.  This one does refuse the string chain on
  all three.  It also collapses on an unannotated probe, where the sentinel turns into a false
  rejection: pyright refuses `has_status("PAID")`, and mypy and pyright refuse a numeric assertion that
  is correct.

So the flat protocol is the only shape measured that refuses anything at all while the hook keeps
working, and what it cannot refuse is a value whose own view is narrower than the umbrella: overload
resolution has no way to say "only if no earlier rung matched".  `str` binds `_CapableT` by being
iterable, and there is no negation to exclude a type that has a view of its own.

Where that leaves the residue is worth naming, because it is not here.  `assert_that()` hands a value
the umbrella claims the whole builder, so `assert_that(mapping_shaped).is_positive()` type-checks off
the chain too and raises when it runs.  Narrowing the chain alone would leave a polled value stricter
than the same value off it, so the repair belongs to the umbrella.  Both are recorded as cases in
`tests/typing_negative_baseline.py`.

Rungs follow the order `assert_that()` dispatches in, since they answer the same question.

Run: `python scripts/generate_poll_protocols.py`
"""

from __future__ import annotations

import ast
import pathlib
import re
import subprocess
import sys
from typing import Final

ROOT = pathlib.Path(__file__).resolve().parent.parent
VIEWS = ROOT / "assertpy2" / "_engine" / "_typing.py"
ENTRY = ROOT / "assertpy2" / "assertpy.py"
TARGET = ROOT / "assertpy2" / "_engine" / "_poll_typing.py"
TARGET_VERDICT = ROOT / "assertpy2" / "_engine" / "_builder_check_typing.py"
TARGET_CAPABLE = ROOT / "assertpy2" / "_engine" / "_capable_typing.py"

sys.path.insert(0, str(ROOT))
from assertpy2._engine._operations import NOT_AN_OPERATION, POLLS, WITHOUT_A_VERDICT  # noqa: E402 - needs the path

# `not_` is declared by hand below: it stays a property here, and the rewrite that turns a chained
# assertion into a chain over the same value would have made it a call
_SKIP = NOT_AN_OPERATION | {name for name, kind in WITHOUT_A_VERDICT.items() if kind == POLLS}

# the verdict twin carries only what reaches a verdict, the same rule the per-view twins follow
_SKIP_FOR_A_VERDICT = NOT_AN_OPERATION | set(WITHOUT_A_VERDICT)

_VERDICT = "_CheckAnyValue"

_HEADER = '''"""The polling twin of every assertion protocol, generated by `scripts/generate_poll_protocols.py`.

Do not edit.  A polling chain replays the assertions recorded on it until they hold together, so it
offers the same assertions the value's own view does and hands back the chain rather than a builder.

Which assertions a chain offers follows the probe's return type, carried in each ``self`` annotation
rather than in the chain's class: see the generator for why the alternative reported a string
assertion on every chain built from an unannotated probe.

A name nobody declares stays open, because `__getattr__` answers it.  That is what keeps
``has_status("PAID")`` working: a dynamic assertion is resolved from the polled value's own
attributes, and no declaration can list it.  It hands back the chain over the same value rather than
one over an unknown, so the assertions after it are still read.  A name that *is* declared still
refuses a chain it was not declared for, measured on mypy and pyright: the hook answers only what the
declarations do not.

What the chain is *not* held to is the surface of a value the capability umbrella claims.  Each
assertion carries a last rung for it, because that is the surface `assert_that()` hands such a value,
and Python's overload resolution has no way to say "only if no earlier rung matched".  So a `str`,
being iterable, reaches rungs the string view does not carry.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
{imports}

    class _SyncPoll(Protocol[_P_co]):
        """A blocking polling chain over a probe returning `_P_co`."""

        def within(self, timeout: float) -> _SyncPoll[_P_co]: ...
        def every(self, interval: float) -> _SyncPoll[_P_co]: ...
        def ignoring(self, *exceptions: type[Exception]) -> _SyncPoll[_P_co]: ...
        @property
        def not_(self) -> _SyncPoll[_P_co]: ...
        @property
        def val(self) -> _P_co: ...
        def __getattr__(self, name: str) -> Callable[..., _SyncPoll[_P_co]]: ...
{sync}

    class _AsyncPoll(Protocol[_P_co]):
        """An awaitable polling chain over a probe returning `_P_co`.

        Awaiting it hands back the ordinary builder over the value that passed, so anything asked
        afterwards is a plain assertion on a settled value rather than a new wait.
        """

        def within(self, timeout: float) -> _AsyncPoll[_P_co]: ...
        def every(self, interval: float) -> _AsyncPoll[_P_co]: ...
        def ignoring(self, *exceptions: type[Exception]) -> _AsyncPoll[_P_co]: ...
        def close(self) -> None: ...
        @property
        def not_(self) -> _AsyncPoll[_P_co]: ...
        def __await__(self) -> Generator[Any, None, AssertionBuilder[_P_co]]: ...
        def __getattr__(self, name: str) -> Callable[..., _AsyncPoll[_P_co]]: ...
{asynchronous}
'''

_IMPORTS = """    import datetime
    import pathlib
{abc}
    from pathlib import Path
    from typing import Any, Protocol, SupportsFloat, TypeVar, overload

    from typing_extensions import TypeIs

    from .._matcher_impls import ClassInfo
    from ..assertpy import AssertionBuilder
    from ..matchers import Matcher
    from ._capable_typing import _Callable, _Orderable, _PathLike
    from ._introspection import MappingLike

    from ._typing import (
        _ArrayT_co,
        _CapableT,
        _FrameT_co,
        _Other,
        _P_co,
        _T_co,
        _U,
    )

    _KeySpecs = Hashable | list[Hashable] | set[Hashable] | frozenset[Hashable]

    _E = TypeVar("_E")
    _N = TypeVar("_N", int, float)
    _K = TypeVar("_K")
    _V = TypeVar("_V")
    _R = TypeVar("_R")
    _B_co = TypeVar("_B_co", bytes, bytearray, covariant=True)
    _U2 = TypeVar("_U2")
    _U3 = TypeVar("_U3")
    _Number = SupportsFloat

    # the rungs below restrict `self` with the annotations `assert_that()` overloads are written with
    _T = TypeVar("_T")
    _P = TypeVar("_P")"""


def _classes(tree: ast.Module) -> dict[str, ast.ClassDef]:
    return {node.name: node for node in ast.walk(tree) if isinstance(node, ast.ClassDef)}


def _bases(node: ast.ClassDef, known: dict[str, ast.ClassDef]) -> list[str]:
    found = []
    for base in node.bases:
        target = base.value if isinstance(base, ast.Subscript) else base
        if isinstance(target, ast.Name) and target.id in known:
            found.append(target.id)
    return found


def _lineage(name: str, known: dict[str, ast.ClassDef], seen: list[str] | None = None) -> list[str]:
    """*name* and every protocol above it, in the order a reader meets them."""
    seen = [] if seen is None else seen
    if name in seen or name not in known:
        return seen
    seen.append(name)
    for base in _bases(known[name], known):
        _lineage(base, known, seen)
    return seen


def _dispatch() -> list[tuple[str, str]]:
    """``(value type, view)`` per `assert_that()` overload, in the order the overloads are written."""
    tree = ast.parse(ENTRY.read_text(encoding="utf-8"))
    found = []
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == "assert_that":
            first = node.args.args[0]
            if first.annotation is not None and node.returns is not None:
                found.append((ast.unparse(first.annotation), ast.unparse(node.returns)))
    return found


def _polled(annotation: str, flavour: str) -> str:
    """The chain over *annotation*, which is what a rung restricts its ``self`` to."""
    return " | ".join(f"{flavour}[{one.strip()}]" for one in annotation.split("|"))


def _handed_back(node: ast.FunctionDef, known: dict[str, ast.ClassDef], flavour: str, *, umbrella: bool) -> str:
    """The chain an assertion hands back, which is a chain over whatever value the view would hold.

    A pivot names the view it lands on, and every view says what its value is, so the chain after a
    pivot keeps a type rather than falling to `Any`: `first()` on a chain over text is a chain over
    text.  The umbrella rung is the exception, since the value it pivots to is the one thing a
    capability does not say.  The verdict twin hands back a verdict instead of a chain, so none of
    that applies to it.
    """
    if flavour == _VERDICT:
        return "AssertionOutcome"
    if node.returns is None:
        return f"{flavour}[Any]"
    rendered = ast.unparse(node.returns)
    if rendered == "Self":
        return f"{flavour}[_P_co]"
    if umbrella:
        return f"{flavour}[Any]"
    head, _, tail = rendered.partition("[")
    arguments = [one.strip() for one in tail[:-1].split(",")] if tail else []
    if head == "AssertionBuilder":
        return f"{flavour}[{arguments[0]}]" if arguments else f"{flavour}[Any]"
    value = _value_of(head, known)
    if value is None or _carries_more_than_its_value(head, known):
        return f"{flavour}[Any]"
    for parameter, argument in zip(_parameters(head, known), arguments, strict=False):
        value = re.sub(rf"\b{re.escape(parameter)}\b", argument, value)
    return f"{flavour}[{value}]"


def _carries_more_than_its_value(name: str, known: dict[str, ast.ClassDef]) -> bool:
    """Whether a landing view offers assertions no chain over its value type could offer.

    `when_called_with()` lands on the invoked view, whose value is the caught message but whose
    surface adds `raised()`, `returned()` and the exception-group assertions.  Reading that view's
    value type would call the chain a chain over text and then answer those eight names off the hook,
    claiming text for whatever they hand back.  A chain over an unknown value is the honest answer.
    """
    dispatched: set[str] = set()
    for _value, view in _dispatch():
        for protocol in _lineage(view.split("[")[0], known):
            dispatched |= {item.name for item in known[protocol].body if isinstance(item, ast.FunctionDef)}
    landing = {
        item.name
        for protocol in _lineage(name, known)
        for item in known[protocol].body
        if isinstance(item, ast.FunctionDef)
    }
    return bool(landing - dispatched)


def _parameters(name: str, known: dict[str, ast.ClassDef]) -> list[str]:
    """The type variables a view is written over, in the order it declares them."""
    node = known.get(name)
    if node is None:
        return []
    for base in node.bases:
        if isinstance(base, ast.Subscript) and isinstance(base.value, ast.Name) and base.value.id == "Protocol":
            return [one.strip() for one in ast.unparse(base.slice).split(",")]
    return []


def _value_of(name: str, known: dict[str, ast.ClassDef]) -> str | None:
    """What a view says its value is, taken from the first `value` declaration up its lineage."""
    for protocol in _lineage(name, known):
        for item in known[protocol].body:
            if isinstance(item, ast.FunctionDef) and item.name == "value" and item.returns is not None:
                return ast.unparse(item.returns)
    return None


def _rewritten(
    node: ast.FunctionDef,
    restriction: str | None,
    flavour: str,
    known: dict[str, ast.ClassDef],
    *,
    umbrella: bool = False,
) -> ast.FunctionDef:
    """The same signature with ``self`` restricted to the chains it applies to and the chain returned."""
    copied = ast.parse(ast.unparse(node)).body[0]
    assert isinstance(copied, ast.FunctionDef)
    own = (copied.args.posonlyargs or copied.args.args)[0]
    if own.annotation is not None:
        # a rung narrowing itself, `is_not_none(self: _ObjectAssertion[T | None])`: about the value
        # kept whole rather than split per member: `_ObjectAssertion[str | None]` is one value that is
        # either, and a chain over each separately is a different question
        inner = ast.unparse(own.annotation)
        own.annotation = ast.Name(id=f"{flavour}[{inner[inner.index('[') + 1 : -1] if '[' in inner else '_P_co'}]")
    elif restriction is not None:
        own.annotation = ast.Name(id=restriction)
    copied.returns = ast.Name(id=_handed_back(node, known, flavour, umbrella=umbrella))
    copied.body = [ast.Expr(value=ast.Constant(value=Ellipsis))]
    copied.decorator_list = [one for one in copied.decorator_list if ast.unparse(one) != "property"]
    return copied


def _narrows_itself(node: ast.FunctionDef) -> bool:
    """Whether the declaration restricts its own ``self``, which is a restriction the view already made."""
    own = (node.args.posonlyargs or node.args.args)[0]
    return own.annotation is not None


def _refines(node: ast.FunctionDef) -> bool:
    """Whether the rung exists only to narrow the value to another view.

    A `TypeIs` predicate tells `assert_that()` which view to hand back next.  A chain has no next view
    to hand back: every rung of such a ladder erases to a chain over an unknown value, so the ladder
    would be one declaration repeated seventeen times.  The plain rung beneath it accepts the same
    predicates, since a `TypeIs` callable is a callable.
    """
    return "TypeIs[" in ast.unparse(node.args)


def _protocols(known: dict[str, ast.ClassDef], flavour: str) -> list[tuple[str, str | None, list[ast.FunctionDef]]]:
    """``(protocol, self restriction, methods)`` for every protocol a dispatched view reaches."""
    ordered_views: list[str] = []
    value_of: dict[str, list[str]] = {}
    for value, view in _dispatch():
        name = view.split("[")[0]
        if name not in known:  # the umbrella hands back the builder itself, which has no protocol
            name = "_Umbrella"
        if name not in ordered_views:
            ordered_views.append(name)
        value_of.setdefault(name, []).append(value)

    named = [view for view in ordered_views if view != "_Umbrella"]
    reach: dict[str, list[str]] = {}
    for view in named:
        for protocol in _lineage(view, known):
            reach.setdefault(protocol, []).append(view)

    found = []
    for protocol, holders in sorted(reach.items(), key=lambda pair: min(named.index(v) for v in pair[1])):
        skip = _SKIP_FOR_A_VERDICT if flavour == _VERDICT else _SKIP
        methods = [
            item
            for item in known[protocol].body
            if isinstance(item, ast.FunctionDef)
            and item.name not in skip
            and not item.name.startswith("_")
            and not _refines(item)
        ]
        if not methods:
            continue
        values = [value for view in holders for value in value_of.get(view, [])]
        universal = len(holders) == len(named)
        restriction = None if universal else _polled(" | ".join(values), flavour)
        found.append((protocol, restriction, methods, len(holders)))
    return found


def _rungs(known: dict[str, ast.ClassDef], flavour: str) -> dict[str, list[ast.FunctionDef]]:
    """``{name: its rungs}``, in the order `assert_that()` would reach them, one per surviving signature.

    A view that redeclares an inherited assertion to keep its own value type renders the same rung
    twice, since both land on the same chain, so the second is dropped here rather than emitted and
    then reported as an overload nothing can select.
    """
    found: dict[str, list[ast.FunctionDef]] = {}
    open_to_any: dict[str, list[ast.FunctionDef]] = {}
    widest: dict[str, tuple[int, ast.FunctionDef]] = {}
    seen: set[str] = set()
    for _protocol, restriction, methods, holders in _protocols(known, flavour):
        for method in methods:
            rendered = _rewritten(method, restriction, flavour, known)
            written = ast.unparse(rendered)
            if written in seen:
                continue
            seen.add(written)
            # a rung open to any chain would make every later one unreachable, so it goes to the end
            narrowed = restriction is not None or _narrows_itself(method)
            (found if narrowed else open_to_any).setdefault(method.name, []).append(rendered)
            if narrowed and holders > widest.get(method.name, (0, method))[0]:
                widest[method.name] = (holders, method)

    # a value the umbrella claims keeps the whole builder, so its rung comes after the named ones.
    # Not written where an open rung follows, which already covers every chain
    for name, (_holders, method) in widest.items():
        if name not in open_to_any:
            # the ordering six ask the value for an ordering, so their umbrella rung asks for one too,
            # the same restriction `_capable_typing` puts on the surface off the chain
            claimed = _RESTRICTED.get(name, "_CapableT")
            rung = _rewritten(method, f"{flavour}[{claimed}]", flavour, known, umbrella=True)
            # a restriction can name the very type a rung above already claims, and then the umbrella
            # rung is that rung written twice: pyright reports the overlap and nothing can select it
            if ast.unparse(rung) not in seen:
                found[name].append(rung)
    for name, rungs in open_to_any.items():
        found.setdefault(name, []).extend(rungs)
    return found


def _body(known: dict[str, ast.ClassDef], flavour: str) -> str:
    lines: list[str] = []
    for rungs in _rungs(known, flavour).values():
        lines.append("")
        for rendered in rungs:
            if len(rungs) > 1 and not any(ast.unparse(one) == "overload" for one in rendered.decorator_list):
                rendered.decorator_list.insert(0, ast.Name(id="overload"))
            lines.append("\n".join(f"        {line}" for line in ast.unparse(rendered).splitlines()))
    return "\n".join(lines)


_ABC_INDENT: Final = "    "
"""The mirrored modules declare their imports inside `if TYPE_CHECKING:`, so the line is written indented."""


def _abc_names(source: pathlib.Path) -> set[str]:
    """The `collections.abc` names one module imports."""
    line = next(
        one
        for one in source.read_text(encoding="utf-8").splitlines()
        if one.strip().startswith("from collections.abc import")
    )
    return {name.strip() for name in line.split("import ", 1)[1].split(",")}


def _abc_import() -> str:
    """The `collections.abc` import for a mirrored module, taken from both modules it is built from.

    The views alone were not enough.  A rung's ``self`` is the annotation an `assert_that()` overload is
    written with, and those live in the entry module, so a name reaching the body from there was emitted
    and never imported.  `Sequence` did exactly that, and every rung carrying it read as an undefined
    name in all 86 places at once.
    """
    names = sorted(_abc_names(VIEWS) | _abc_names(ENTRY) | {"Generator"})
    return f"{_ABC_INDENT}from collections.abc import " + ", ".join(names)


def generate() -> str:
    known = _classes(ast.parse(VIEWS.read_text(encoding="utf-8")))
    return _HEADER.format(
        imports=_IMPORTS.format(abc=_abc_import()),
        sync=_body(known, "_SyncPoll"),
        asynchronous=_body(known, "_AsyncPoll"),
    )


def generate_verdict() -> str:
    known = _classes(ast.parse(VIEWS.read_text(encoding="utf-8")))
    matchers = "    from ..matchers import Matcher"
    imports = _IMPORTS.format(abc=_abc_import()).replace(
        matchers, matchers + "\n    from ..outcome import AssertionOutcome"
    )
    return _VERDICT_HEADER.format(imports=imports, body=_body(known, _VERDICT))


_VERDICT_HEADER = '''"""The verdict twin of a value the builder holds.

Generated by `scripts/generate_poll_protocols.py`; do not edit.  `check()` on a typed view hands back
that view's own twin.  This is the one a value reaches through the builder, which is where an element
pivot and the capability umbrella both land.

Flat and self-dispatched for the same measured reason the polling twins are: overloading `check()` on
the builder's own type variable put an `AssertionBuilder[Any]` on the first rung, and every chain built
from a payload typed `dict[str, Any]` then read as a string.  A rung per assertion inverts that.

A name nobody declares stays open, because `__getattr__` answers it: a dynamic assertion is resolved
from the value's own attributes and reaches this proxy too.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
{imports}

    class _CheckAnyValue(Protocol[_P_co]):
        """The verdict surface of a value reached through the builder rather than through a view."""

        @property
        def not_(self) -> _CheckAnyValue[_P_co]: ...
        def __getattr__(self, name: str) -> Callable[..., AssertionOutcome]: ...
{body}
'''


_CAPABLE = "_CapableAssertion"

_ASKS_A_SHAPE: Final = {
    # ordering: every one reaches `_engine._ordering.compare`, which orders the pair with `<`.  Measured
    # on a class carrying one operator at a time, `__lt__` was the only one any of the six ran with, so
    # keying on `__gt__`, which is what `is_positive` looks like it needs, would refuse a type that works
    "is_positive": "_Orderable",
    "is_negative": "_Orderable",
    "is_greater_than": "_Orderable",
    "is_greater_than_or_equal_to": "_Orderable",
    "is_less_than": "_Orderable",
    "is_less_than_or_equal_to": "_Orderable",
    # the filesystem: `isinstance(val, (str, os.PathLike))`, and a `str` never reaches here because the
    # string overload is above the umbrella.  What is left is the structural half, `__fspath__`
    "exists": "_PathLike",
    "does_not_exist": "_PathLike",
    "is_file": "_PathLike",
    "is_directory": "_PathLike",
    "is_named": "_PathLike",
    "is_child_of": "_PathLike",
    "is_readable": "_PathLike",
    "is_writable": "_PathLike",
    "is_executable": "_PathLike",
    # the call: `callable(val)`, which is structural.  A capable value can be callable, and the
    # callable view sits below the umbrella, so this is the only place such a value is described
    "raises": "_Callable",
    "does_not_raise": "_Callable",
    "warns": "_Callable",
    "does_not_warn": "_Callable",
    "when_called_with": "_Callable",
}
"""What each of these asks the value for: a capability it can carry, keyed on what the runtime reads.

Measured one capability at a time, because four separate readings were wrong when the fixture was
missing the one thing the assertion reached for: `is_positive` looks like `__gt__` and is held by
`__lt__`, `is_between` refuses a number that cannot be ordered, and `when_called_with()` refuses
everything until `raises()` has been called before it.
"""

_ASKS_A_TYPE: Final = {
    # whole numbers: `isinstance(val, int)` with `bool` refused beside it, a plain check rather than the
    # registration the rest of the numeric family uses.  The rung above claims `int | float`, so pyright reports
    # the overlap; recorded rather than traded for a wider key that would let a float through
    "is_even": "int",
    "is_odd": "int",
    "is_divisible_by": "int",
    # text: `isinstance(val, str)`
    "matches": "str",
    "does_not_match": "str",
    "is_upper": "str",
    "is_lower": "str",
    "is_alpha": "str",
    "is_digit": "str",
    "is_alphanumeric": "str",
    "is_whitespace": "str",
    "is_equal_to_ignoring_case": "str",
    "is_equal_to_ignoring_whitespace": "str",
    "starts_with_ignoring_case": "str",
    "ends_with_ignoring_case": "str",
    "matches_with_groups": "str",
    "extracting_group": "str",
    # dates: `isinstance(val, datetime.datetime)`, and exactly that rather than `date`
    "is_before": "datetime.datetime",
    "is_after": "datetime.datetime",
    "is_before_or_equal_to": "datetime.datetime",
    "is_after_or_equal_to": "datetime.datetime",
    "is_equal_to_ignoring_time": "datetime.datetime",
    "is_equal_to_ignoring_seconds": "datetime.datetime",
    "is_equal_to_ignoring_milliseconds": "datetime.datetime",
    # bytes: `isinstance(val, (bytes, bytearray))`
    "is_hex_equal_to": "bytes | bytearray",
    "is_valid_utf8": "bytes | bytearray",
    "is_valid_encoding": "bytes | bytearray",
    "contains_bytes": "bytes | bytearray",
    "starts_with_bytes": "bytes | bytearray",
    "has_byte_at": "bytes | bytearray",
    "decoded_as": "bytes | bytearray",
}
"""Asked of a type no value reaching the umbrella can be, because each of those has an overload above it.

Declared rather than left out, and that distinction is the whole of it: an assertion the façade does not
declare is answered by `__getattr__` and refuses nothing.  Measured that way first, and text, dates and
bytes all still type-checked on a capable value until the rung was written.
"""

_RESTRICTED: Final = _ASKS_A_SHAPE | _ASKS_A_TYPE
"""Every rung the façade narrows, and what it asks the value for.

The ten numeric assertions that are not here are the one family left open, and the reason is measured.
Their gate is `isinstance(val, numbers.Number)`, which a class earns by registration and no checker can
read.  Every structural stand-in was wrong in one direction or the other: without registration all ten
refuse whatever the value carries, and with it `is_zero()` runs on a class that has no `__float__` at
all, so keying them on `SupportsFloat` refused a call that works.  A false rejection is the more
expensive of the two here, which is what leaves them open.
"""


_BY_HAND: Final = frozenset(
    {
        "is_not_none",
        "is_instance_of",
        "is_instance_of_any",
        "first",
        "last",
        "element",
        "mapped",
        "single",
        "satisfies",
        "eventually",
        "eventually_sync",
        "builder",
        "error",
        "check",
    }
)
"""Declared in the header instead, because the builder declares each of them as a ladder for checkers.

Flattened to the mixin's own signature they would lose what the ladder buys: the narrowing out of
, the narrowing to a checked class, and the key type a pivot lands on.
"""


def _builder_surface() -> list[ast.FunctionDef]:
    """Every public assertion the builder carries, read from the mixins it is composed of.

    Read from the runtime rather than from the views, because the façade replaces the *builder* in one
    overload and has to offer what the builder offers.  Taking the views instead would narrow by
    accident: a view carries what one value type answers, and the value this stands in for is the one
    the library recognised without being able to name.
    """
    found: dict[str, ast.FunctionDef] = {}
    for path in sorted((ROOT / "assertpy2").glob("*.py")):
        module = ast.parse(path.read_text(encoding="utf-8"))
        for node in ast.walk(module):
            if not isinstance(node, ast.ClassDef) or not node.name.endswith("Mixin"):
                continue
            for item in node.body:
                if isinstance(item, ast.FunctionDef) and not item.name.startswith("_"):
                    if item.name in _BY_HAND:
                        continue
                    found.setdefault(item.name, item)
    return [found[name] for name in sorted(found)]


def _capable_declaration(node: ast.FunctionDef) -> str:
    """One method of the façade: the runtime's own signature, with the body and the docstring gone."""
    rendered = ast.parse(ast.unparse(node)).body[0]
    if not isinstance(rendered, ast.FunctionDef):  # pragma: no cover - every entry here is a function
        raise TypeError(node.name)
    rendered.decorator_list = []
    rendered.body = [ast.Expr(value=ast.Constant(value=...))]
    # every default becomes `...`, the way a stub spells one: copied verbatim they carry names that
    # live in the mixin and nowhere else, and `_UNSET` arrived here as an undefined name
    elided = [ast.Constant(value=...) for _ in rendered.args.defaults]
    rendered.args.defaults = elided
    rendered.args.kw_defaults = [None if one is None else ast.Constant(value=...) for one in rendered.args.kw_defaults]
    if node.name in _RESTRICTED:
        asked = _RESTRICTED[node.name]
        rendered.args.args[0].annotation = ast.parse(f"{_CAPABLE}[{asked}]", mode="eval").body
        # `Self` needs an unannotated receiver, so a restricted rung has to name what it hands back
        rendered.returns = ast.parse(f"{_CAPABLE}[_CapableT_co]", mode="eval").body
    return ast.unparse(rendered)


def generate_capable() -> str:
    body = "\n".join(
        "\n".join(f"        {line}" for line in _capable_declaration(node).splitlines()) for node in _builder_surface()
    )
    return _CAPABLE_HEADER.format(body=body)


_CAPABLE_HEADER = '''"""The surface of a value the capability umbrella claims.

Generated by `scripts/generate_poll_protocols.py`.

Do not edit.  `assert_that()` hands this back for a value that answers to some capability and to no
overload by name: a model, a dataclass, an HTTP response, a container of one\'s own.  It offers what the
builder offers, because that is what such a value used to get and none of it can be taken away without
refusing a call that runs.

What it exists to add is one restriction.  The six ordering assertions read the value with an ordering,
so a builder over a value that has none is not one they can be asked of.  Before this,
`assert_that(a_mapping).is_positive()` type-checked on ty, mypy and Pyright, the three gated then, and raised
ran.

A protocol rather than a subclass of the builder: narrowing ``self`` in a subclass is an invalid
override, measured on ty, and the working precedents that narrow it all end in a rung open to anything,
which is what a refusal cannot have.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import datetime
    import logging
    from collections.abc import Callable, Collection, Hashable, Iterable, Mapping, Sized
    from pathlib import Path
    from typing import Any, Protocol, SupportsFloat, TypeVar, overload

    from typing_extensions import TypeIs

    from .._matcher_impls import ClassInfo
    from ..assertpy import AssertionBuilder
    from ..matchers import Matcher
    from ._builder_check_typing import _CheckAnyValue
    from ._compat import Self
    from ._poll_typing import _AsyncPoll, _SyncPoll
    from ._typing import _E, _K, _R, _U, _V

    # covariant: the façade only ever hands the subject back, through `value`
    _CapableT_co = TypeVar("_CapableT_co", covariant=True)
    _U2 = TypeVar("_U2")
    _U3 = TypeVar("_U3")
    _E_co = TypeVar("_E_co", covariant=True)

    class _Orderable(Protocol):
        """A value with an ordering, which is all the relational assertions ask of one."""

        def __lt__(self, other: Any, /) -> Any: ...

    class _PathLike(Protocol):
        """A value the filesystem assertions can read a path out of, spelled as `os.PathLike` spells it."""

        def __fspath__(self) -> Any: ...

    class _Callable(Protocol):
        """A value the exception and warning assertions can call, which is what `callable()` asks."""

        def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

    class _ElementSource(Protocol[_E_co]):
        """Anything whose value is a collection of `_E_co`, spelled the way the builder spells it."""

        @property
        def value(self) -> Collection[_E_co]: ...

    class _CapableAssertion(Protocol[_CapableT_co]):
        """What a value the umbrella claims can be asked."""

        # the data the builder carries, spelled as `_MixinBase` spells it.  Set in `__init__` and so absent from
        # `dir()` of the class, which is how they were missed: left to `__getattr__` they read as callables, and
        # `assert_that(a_capable_value).description.upper()` was refused
        val: Any
        description: str
        kind: str | None
        expected: type[BaseException] | None
        logger: logging.LoggerAdapter[Any]

        @property
        def value(self) -> _CapableT_co: ...
        @property
        def not_(self) -> Self: ...
        def __getattr__(self, name: str) -> Callable[..., Self]: ...

        # the ladders the builder declares for checkers, carried across rather than flattened.  This replaces the
        # builder in one overload, so a narrowing lost here is lost for every value the umbrella claims, and
        # `first()` on a mapping-shaped value would stop naming its key type
        @overload
        def is_not_none(self: _CapableAssertion[_U | None]) -> _CapableAssertion[_U]: ...
        @overload
        def is_not_none(self) -> Self: ...
        @overload
        def is_instance_of(self, some_class: tuple[type[_U], type[_U2]]) -> AssertionBuilder[_U | _U2]: ...
        @overload
        def is_instance_of(
            self, some_class: tuple[type[_U], type[_U2], type[_U3]]
        ) -> AssertionBuilder[_U | _U2 | _U3]: ...
        @overload
        def is_instance_of(self, some_class: type[_U]) -> AssertionBuilder[_U]: ...
        @overload
        def is_instance_of(self, some_class: ClassInfo) -> Self: ...
        @overload
        def is_instance_of_any(self, first: type[_U], second: type[_U2], /) -> AssertionBuilder[_U | _U2]: ...
        @overload
        def is_instance_of_any(
            self, first: type[_U], second: type[_U2], third: type[_U3], /
        ) -> AssertionBuilder[_U | _U2 | _U3]: ...
        @overload
        def is_instance_of_any(self, *some_classes: ClassInfo) -> Self: ...
        @overload
        def first(self: _CapableAssertion[Mapping[_K, _V]]) -> AssertionBuilder[_K]: ...
        @overload
        def first(self: _ElementSource[_E]) -> AssertionBuilder[_E]: ...
        @overload
        def first(self) -> Self: ...
        @overload
        def last(self: _CapableAssertion[Mapping[_K, _V]]) -> AssertionBuilder[_K]: ...
        @overload
        def last(self: _ElementSource[_E]) -> AssertionBuilder[_E]: ...
        @overload
        def last(self) -> Self: ...
        @overload
        def element(self: _CapableAssertion[Mapping[_K, _V]], index: int) -> AssertionBuilder[_K]: ...
        @overload
        def element(self: _ElementSource[_E], index: int) -> AssertionBuilder[_E]: ...
        @overload
        def element(self, index: int) -> Self: ...
        @overload
        def mapped(self: _ElementSource[_E], func: Callable[[_E], _R]) -> AssertionBuilder[list[_R]]: ...
        @overload
        def mapped(self, func: Callable[..., Any]) -> Self: ...
        @overload
        def single(self: _CapableAssertion[Mapping[_K, _V]]) -> AssertionBuilder[_K]: ...
        @overload
        def single(self: _ElementSource[_E]) -> AssertionBuilder[_E]: ...
        @overload
        def single(self) -> Self: ...
        @overload
        def satisfies(self, matcher: Callable[[Any], TypeIs[_U]]) -> AssertionBuilder[_U]: ...
        @overload
        def satisfies(self, matcher: Matcher[Any] | Callable[..., bool]) -> Self: ...
        # the two polling pivots, which live on the builder rather than on a mixin.  Over `Any` rather than over
        # the subject: no capability says whether the value is callable, so the chain keeps every rung open.  Left
        # to `__getattr__` they came back as this facade over the callable that was polled, not over its result
        def eventually(
            self,
            *,
            timeout: float = ...,
            interval: float = ...,
            ignoring: type[Exception] | tuple[type[Exception], ...] = ...,
            trace: bool = ...,
        ) -> _AsyncPoll[Any]: ...
        def eventually_sync(
            self,
            *,
            timeout: float = ...,
            interval: float = ...,
            ignoring: type[Exception] | tuple[type[Exception], ...] = ...,
            trace: bool = ...,
        ) -> _SyncPoll[Any]: ...
        # the builder's own two helpers, also off the mixins.  `builder()` is a pivot: left to `__getattr__` it
        # read as this facade over the value that was already here
        def builder(
            self,
            val: Any,
            description: str = ...,
            kind: str | None = ...,
            expected: Any = ...,
            logger: Any = ...,
            origin: Any = ...,
        ) -> AssertionBuilder[Any]: ...
        def error(
            self,
            msg: str,
            *,
            actual: Any = ...,
            expected: Any = ...,
            diff: Any = ...,
            trace: Any = ...,
            suppress_context: bool = ...,
        ) -> Self: ...
        def check(self) -> _CheckAnyValue[_CapableT_co]: ...
{body}
'''


if __name__ == "__main__":
    TARGET.write_text(generate(), encoding="utf-8", newline="")
    TARGET_VERDICT.write_text(generate_verdict(), encoding="utf-8", newline="")
    TARGET_CAPABLE.write_text(generate_capable(), encoding="utf-8", newline="")
    for written in (TARGET, TARGET_VERDICT, TARGET_CAPABLE):
        subprocess.run(["uv", "run", "ruff", "format", str(written)], cwd=ROOT, check=False, capture_output=True)
        fix = ["uv", "run", "ruff", "check", "--fix", str(written)]
        subprocess.run(fix, cwd=ROOT, check=False, capture_output=True)
        print(f"wrote {written.relative_to(ROOT)}")
