"""Generate the verdict twins of the assertion protocols.

`check()` runs one assertion for its verdict instead of its failure, so every assertion is available
through it with the return type replaced.  Written by hand that would be a second copy of 182
declarations, kept in step with the first by nobody: the check surface would drift silently, which is
the failure this project has a parity gate for everywhere else.

So it is generated from the protocols themselves, and `tests/test_check_protocols.py` regenerates and
compares, which makes the drift impossible rather than merely visible.

What is *not* generated: `.not_`, which is the same proxy under both, and the dispatch in
`assert_that()`, where the checker-specific compromises live.  Those are decisions, and a generator
that made them would be making them where nobody reads.

Run: `python scripts/generate_check_protocols.py`
"""

from __future__ import annotations

import ast
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "assertpy2" / "_engine" / "_typing.py"
TARGET = ROOT / "assertpy2" / "_engine" / "_check_typing.py"

sys.path.insert(0, str(ROOT))
from assertpy2._engine._operations import NOT_AN_OPERATION, WITHOUT_A_VERDICT  # noqa: E402 - needs the path above

_SKIP = set(WITHOUT_A_VERDICT) | NOT_AN_OPERATION

_HEADER = '''"""The verdict twin of every assertion protocol, generated by `scripts/generate_check_protocols.py`.

Do not edit.  `check()` hands back the twin of the view it was reached from, so an assertion asked for
a verdict is checked against the same value type it would be checked against normally:
`assert_that(1).check().starts_with("x")` is a type error rather than a runtime one.

Only operations that reach a verdict appear.  A pivot or a configurer has none to report, and both
proxies refuse them at runtime; see `assertpy2/_engine/_operations.py`.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    import datetime
{abc}
    from pathlib import Path
    from typing import Any, Protocol, SupportsFloat, TypeVar, overload

    from typing_extensions import TypeIs

    from ..errors import AssertionOutcome
    from ..matchers import Matcher
    from ._compat import Self
    from ._introspection import MappingLike

    # the type variables and the object view come from the module these twins mirror, so a change
    # there cannot leave the two disagreeing about what a variable is bound to
    from ._typing import (
        _ArrayT_co,
        _CapableT,
        _FrameT_co,
        _ObjectAssertion,
        _Other,
        _P_co,
        _T_co,
        _U,
    )

    _KeySpecs = Hashable | list[Hashable] | set[Hashable] | frozenset[Hashable]

    _E = TypeVar("_E")
    _N = TypeVar("_N", int, float)
    _K = TypeVar("_K")
    _V = TypeVar("_V")
    _B_co = TypeVar("_B_co", bytes, bytearray, covariant=True)
    _Number = SupportsFloat
'''


def _twin(name: str) -> str:
    return name.replace("_", "_Check", 1) if name.startswith("_") else f"_Check{name}"


def _returns_a_verdict(node: ast.FunctionDef) -> ast.FunctionDef:
    """The same signature with the return type replaced: a verdict is reported, not a chain."""
    copied = ast.parse(ast.unparse(node)).body[0]
    assert isinstance(copied, ast.FunctionDef)
    copied.returns = ast.Name(id="AssertionOutcome")
    copied.body = [ast.Expr(value=ast.Constant(value=Ellipsis))]
    # `property` goes: a verdict is reported by a call, not read off an attribute
    copied.decorator_list = [d for d in copied.decorator_list if ast.unparse(d) != "property"]
    return copied


def generate() -> str:
    tree = ast.parse(SOURCE.read_text(encoding="utf-8"))
    protocols = [n for n in ast.walk(tree) if isinstance(n, ast.ClassDef) and n.name.endswith("Assertion")]
    # the abc import is copied from the module being mirrored rather than repeated here: a name added
    # there and not here read as undefined in the generated file, which only pyright's baseline caught
    abc = next(
        line
        for line in pathlib.Path(SOURCE).read_text(encoding="utf-8").splitlines()
        if line.strip().startswith("from collections.abc import")
    )
    lines = [_HEADER.format(abc=abc)]
    for node in protocols:
        bases = []
        for base in node.bases:
            target = base.value if isinstance(base, ast.Subscript) else base
            if isinstance(target, ast.Name) and target.id.endswith("Assertion"):
                bases.append(ast.unparse(base).replace(target.id, _twin(target.id)))
            else:
                bases.append(ast.unparse(base))
        methods = [
            item
            for item in node.body
            if isinstance(item, ast.FunctionDef) and item.name not in _SKIP and not item.name.startswith("_")
        ]
        lines.append(f"\n    class {_twin(node.name)}({', '.join(bases)}):")
        lines.append(f'        """The verdict twin of `{node.name}`."""\n')
        if not methods:
            lines.append("        @property")
            lines.append("        def not_(self) -> Self: ...")
            lines.append("")
            continue
        for method in methods:
            # the decorators come out of `_returns_a_verdict`, which keeps every one but `property`.
            # Rendering them separately as well is how `@overload` was emitted twice on every rung
            rendered = ast.unparse(_returns_a_verdict(method))
            lines.append("\n".join(f"        {line}" for line in rendered.splitlines()))
        lines.append("        @property")
        lines.append("        def not_(self) -> Self: ...")
        lines.append("")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    TARGET.write_text(generate(), encoding="utf-8", newline="")
    subprocess.run(["uv", "run", "ruff", "format", str(TARGET)], cwd=ROOT, check=False, capture_output=True)
    subprocess.run(["uv", "run", "ruff", "check", "--fix", str(TARGET)], cwd=ROOT, check=False, capture_output=True)
    print(f"wrote {TARGET.relative_to(ROOT)}")
