"""Generate the polling twins of the assertion protocols.

A polling chain records the assertion and replays it until it holds, so every assertion is available
through it with the return type replaced by the chain itself.  Both builders resolve the name at run
time through `__getattr__`, which no checker can read: until this existed, a polling chain was `Any`
from the first assertion onwards, and `eventually_sync().method_that_does_not_exist()` passed all
three checkers.

The twins are one flat protocol per flavour rather than one per view, and each assertion carries the
value types it applies to in its own ``self`` annotation.  A view per value type would have to be
chosen by `eventually_sync()`, whose overloads see the probe's return type: measured, a probe with no
annotation returns `Any`, an `Any` self matches the first rung, and every checker then reported a
string assertion on a chain that polls anything.  Per-assertion ``self`` inverts that: an `Any` chain
matches every rung and keeps the freedom it has today, and an annotated one is held to its type.

Rungs follow the order `assert_that()` dispatches in, since they answer the same question.

Run: `python scripts/generate_poll_protocols.py`
"""

from __future__ import annotations

import ast
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
VIEWS = ROOT / "assertpy2" / "_engine" / "_typing.py"
ENTRY = ROOT / "assertpy2" / "assertpy.py"
TARGET = ROOT / "assertpy2" / "_engine" / "_poll_typing.py"
TARGET_VERDICT = ROOT / "assertpy2" / "_engine" / "_builder_check_typing.py"

sys.path.insert(0, str(ROOT))
from assertpy2._engine._operations import NOT_AN_OPERATION, POLLS, WITHOUT_A_VERDICT  # noqa: E402 - needs the path

# `not_` is declared by hand below: it stays a property here, and the rewrite that turns a chained
# assertion into a chain over the same value would have made it a call
_SKIP = NOT_AN_OPERATION | {name for name, kind in WITHOUT_A_VERDICT.items() if kind == POLLS}

# the verdict twin carries only what reaches a verdict, the same rule the per-view twins follow
_SKIP_FOR_A_VERDICT = NOT_AN_OPERATION | set(WITHOUT_A_VERDICT)

_VERDICT = "_CheckAnyValue"

_HEADER = '''"""The polling twin of every assertion protocol, generated by `scripts/generate_poll_protocols.py`.

Do not edit.  A polling chain replays the assertions recorded on it until they hold together, so it
offers the same assertions the value's own view does and hands back the chain rather than a builder.

Which assertions a chain offers follows the probe's return type, carried in each ``self`` annotation
rather than in the chain's class: see the generator for why the alternative reported a string
assertion on every chain built from an unannotated probe.

A name nobody declares stays open, because `__getattr__` answers it.  That is what keeps
``has_status("PAID")`` working: a dynamic assertion is resolved from the polled value's own
attributes, and no declaration can list it.  It hands back the chain over the same value rather than
one over an unknown, so the assertions after it are still read.  A name that *is* declared still
refuses a chain it was not declared for, measured on mypy and pyright: the hook answers only what the
declarations do not.

What the chain is *not* held to is the surface of a value the capability umbrella claims.  Each
assertion carries a last rung for it, because that is the surface `assert_that()` hands such a value,
and Python's overload resolution has no way to say "only if no earlier rung matched".  So a `str`,
being iterable, reaches rungs the string view does not carry.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
{imports}

    class _SyncPoll(Protocol[_P_co]):
        """A blocking polling chain over a probe returning `_P_co`."""

        def within(self, timeout: float) -> _SyncPoll[_P_co]: ...
        def every(self, interval: float) -> _SyncPoll[_P_co]: ...
        def ignoring(self, *exceptions: type[Exception]) -> _SyncPoll[_P_co]: ...
        @property
        def not_(self) -> _SyncPoll[_P_co]: ...
        @property
        def val(self) -> _P_co: ...
        def __getattr__(self, name: str) -> Callable[..., _SyncPoll[_P_co]]: ...
{sync}

    class _AsyncPoll(Protocol[_P_co]):
        """An awaitable polling chain over a probe returning `_P_co`.

        Awaiting it hands back the ordinary builder over the value that passed, so anything asked
        afterwards is a plain assertion on a settled value rather than a new wait.
        """

        def within(self, timeout: float) -> _AsyncPoll[_P_co]: ...
        def every(self, interval: float) -> _AsyncPoll[_P_co]: ...
        def ignoring(self, *exceptions: type[Exception]) -> _AsyncPoll[_P_co]: ...
        def close(self) -> None: ...
        @property
        def not_(self) -> _AsyncPoll[_P_co]: ...
        def __await__(self) -> Generator[Any, None, AssertionBuilder[_P_co]]: ...
        def __getattr__(self, name: str) -> Callable[..., _AsyncPoll[_P_co]]: ...
{asynchronous}
'''

_IMPORTS = """    import datetime
    import pathlib
{abc}
    from pathlib import Path
    from typing import Any, Protocol, SupportsFloat, TypeVar, overload

    from typing_extensions import TypeIs

    from ..assertpy import AssertionBuilder
    from ..matchers import Matcher
    from ._introspection import MappingLike

    from ._typing import (
        _ArrayT_co,
        _CapableT,
        _FrameT_co,
        _Other,
        _P_co,
        _T_co,
        _U,
    )

    _KeySpecs = Hashable | list[Hashable] | set[Hashable] | frozenset[Hashable]

    _E = TypeVar("_E")
    _N = TypeVar("_N", int, float)
    _K = TypeVar("_K")
    _V = TypeVar("_V")
    _R = TypeVar("_R")
    _B_co = TypeVar("_B_co", bytes, bytearray, covariant=True)
    _Number = SupportsFloat

    # the rungs below restrict `self` with the annotations `assert_that()` overloads are written with
    _T = TypeVar("_T")
    _P = TypeVar("_P")"""


def _classes(tree: ast.Module) -> dict[str, ast.ClassDef]:
    return {node.name: node for node in ast.walk(tree) if isinstance(node, ast.ClassDef)}


def _bases(node: ast.ClassDef, known: dict[str, ast.ClassDef]) -> list[str]:
    found = []
    for base in node.bases:
        target = base.value if isinstance(base, ast.Subscript) else base
        if isinstance(target, ast.Name) and target.id in known:
            found.append(target.id)
    return found


def _lineage(name: str, known: dict[str, ast.ClassDef], seen: list[str] | None = None) -> list[str]:
    """*name* and every protocol above it, in the order a reader meets them."""
    seen = [] if seen is None else seen
    if name in seen or name not in known:
        return seen
    seen.append(name)
    for base in _bases(known[name], known):
        _lineage(base, known, seen)
    return seen


def _dispatch() -> list[tuple[str, str]]:
    """``(value type, view)`` per `assert_that()` overload, in the order the overloads are written."""
    tree = ast.parse(ENTRY.read_text(encoding="utf-8"))
    found = []
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == "assert_that":
            first = node.args.args[0]
            if first.annotation is not None and node.returns is not None:
                found.append((ast.unparse(first.annotation), ast.unparse(node.returns)))
    return found


def _polled(annotation: str, flavour: str) -> str:
    """The chain over *annotation*, which is what a rung restricts its ``self`` to."""
    return " | ".join(f"{flavour}[{one.strip()}]" for one in annotation.split("|"))


def _handed_back(node: ast.FunctionDef, known: dict[str, ast.ClassDef], flavour: str, *, umbrella: bool) -> str:
    """The chain an assertion hands back, which is a chain over whatever value the view would hold.

    A pivot names the view it lands on, and every view says what its value is, so the chain after a
    pivot keeps a type rather than falling to `Any`: `first()` on a chain over text is a chain over
    text.  The umbrella rung is the exception, since the value it pivots to is the one thing a
    capability does not say.  The verdict twin hands back a verdict instead of a chain, so none of
    that applies to it.
    """
    if flavour == _VERDICT:
        return "AssertionOutcome"
    if node.returns is None:
        return f"{flavour}[Any]"
    rendered = ast.unparse(node.returns)
    if rendered == "Self":
        return f"{flavour}[_P_co]"
    if umbrella:
        return f"{flavour}[Any]"
    head, _, tail = rendered.partition("[")
    arguments = [one.strip() for one in tail[:-1].split(",")] if tail else []
    if head == "AssertionBuilder":
        return f"{flavour}[{arguments[0]}]" if arguments else f"{flavour}[Any]"
    value = _value_of(head, known)
    if value is None or _carries_more_than_its_value(head, known):
        return f"{flavour}[Any]"
    for parameter, argument in zip(_parameters(head, known), arguments, strict=False):
        value = re.sub(rf"\b{re.escape(parameter)}\b", argument, value)
    return f"{flavour}[{value}]"


def _carries_more_than_its_value(name: str, known: dict[str, ast.ClassDef]) -> bool:
    """Whether a landing view offers assertions no chain over its value type could offer.

    `when_called_with()` lands on the invoked view, whose value is the caught message but whose
    surface adds `raised()`, `returned()` and the exception-group assertions.  Reading that view's
    value type would call the chain a chain over text and then answer those eight names off the hook,
    claiming text for whatever they hand back.  A chain over an unknown value is the honest answer.
    """
    dispatched: set[str] = set()
    for _value, view in _dispatch():
        for protocol in _lineage(view.split("[")[0], known):
            dispatched |= {item.name for item in known[protocol].body if isinstance(item, ast.FunctionDef)}
    landing = {
        item.name
        for protocol in _lineage(name, known)
        for item in known[protocol].body
        if isinstance(item, ast.FunctionDef)
    }
    return bool(landing - dispatched)


def _parameters(name: str, known: dict[str, ast.ClassDef]) -> list[str]:
    """The type variables a view is written over, in the order it declares them."""
    node = known.get(name)
    if node is None:
        return []
    for base in node.bases:
        if isinstance(base, ast.Subscript) and isinstance(base.value, ast.Name) and base.value.id == "Protocol":
            return [one.strip() for one in ast.unparse(base.slice).split(",")]
    return []


def _value_of(name: str, known: dict[str, ast.ClassDef]) -> str | None:
    """What a view says its value is, taken from the first `value` declaration up its lineage."""
    for protocol in _lineage(name, known):
        for item in known[protocol].body:
            if isinstance(item, ast.FunctionDef) and item.name == "value" and item.returns is not None:
                return ast.unparse(item.returns)
    return None


def _rewritten(
    node: ast.FunctionDef,
    restriction: str | None,
    flavour: str,
    known: dict[str, ast.ClassDef],
    *,
    umbrella: bool = False,
) -> ast.FunctionDef:
    """The same signature with ``self`` restricted to the chains it applies to and the chain returned."""
    copied = ast.parse(ast.unparse(node)).body[0]
    assert isinstance(copied, ast.FunctionDef)
    own = (copied.args.posonlyargs or copied.args.args)[0]
    if own.annotation is not None:
        # a rung narrowing itself, `is_not_none(self: _ObjectAssertion[T | None])`: about the value
        # kept whole rather than split per member: `_ObjectAssertion[str | None]` is one value that is
        # either, and a chain over each separately is a different question
        inner = ast.unparse(own.annotation)
        own.annotation = ast.Name(id=f"{flavour}[{inner[inner.index('[') + 1 : -1] if '[' in inner else '_P_co'}]")
    elif restriction is not None:
        own.annotation = ast.Name(id=restriction)
    copied.returns = ast.Name(id=_handed_back(node, known, flavour, umbrella=umbrella))
    copied.body = [ast.Expr(value=ast.Constant(value=Ellipsis))]
    copied.decorator_list = [one for one in copied.decorator_list if ast.unparse(one) != "property"]
    return copied


def _narrows_itself(node: ast.FunctionDef) -> bool:
    """Whether the declaration restricts its own ``self``, which is a restriction the view already made."""
    own = (node.args.posonlyargs or node.args.args)[0]
    return own.annotation is not None


def _refines(node: ast.FunctionDef) -> bool:
    """Whether the rung exists only to narrow the value to another view.

    A `TypeIs` predicate tells `assert_that()` which view to hand back next.  A chain has no next view
    to hand back: every rung of such a ladder erases to a chain over an unknown value, so the ladder
    would be one declaration repeated seventeen times.  The plain rung beneath it accepts the same
    predicates, since a `TypeIs` callable is a callable.
    """
    return "TypeIs[" in ast.unparse(node.args)


def _protocols(known: dict[str, ast.ClassDef], flavour: str) -> list[tuple[str, str | None, list[ast.FunctionDef]]]:
    """``(protocol, self restriction, methods)`` for every protocol a dispatched view reaches."""
    ordered_views: list[str] = []
    value_of: dict[str, list[str]] = {}
    for value, view in _dispatch():
        name = view.split("[")[0]
        if name not in known:  # the umbrella hands back the builder itself, which has no protocol
            name = "_Umbrella"
        if name not in ordered_views:
            ordered_views.append(name)
        value_of.setdefault(name, []).append(value)

    named = [view for view in ordered_views if view != "_Umbrella"]
    reach: dict[str, list[str]] = {}
    for view in named:
        for protocol in _lineage(view, known):
            reach.setdefault(protocol, []).append(view)

    found = []
    for protocol, holders in sorted(reach.items(), key=lambda pair: min(named.index(v) for v in pair[1])):
        skip = _SKIP_FOR_A_VERDICT if flavour == _VERDICT else _SKIP
        methods = [
            item
            for item in known[protocol].body
            if isinstance(item, ast.FunctionDef)
            and item.name not in skip
            and not item.name.startswith("_")
            and not _refines(item)
        ]
        if not methods:
            continue
        values = [value for view in holders for value in value_of.get(view, [])]
        universal = len(holders) == len(named)
        restriction = None if universal else _polled(" | ".join(values), flavour)
        found.append((protocol, restriction, methods, len(holders)))
    return found


def _rungs(known: dict[str, ast.ClassDef], flavour: str) -> dict[str, list[ast.FunctionDef]]:
    """``{name: its rungs}``, in the order `assert_that()` would reach them, one per surviving signature.

    A view that redeclares an inherited assertion to keep its own value type renders the same rung
    twice, since both land on the same chain, so the second is dropped here rather than emitted and
    then reported as an overload nothing can select.
    """
    found: dict[str, list[ast.FunctionDef]] = {}
    open_to_any: dict[str, list[ast.FunctionDef]] = {}
    widest: dict[str, tuple[int, ast.FunctionDef]] = {}
    seen: set[str] = set()
    for _protocol, restriction, methods, holders in _protocols(known, flavour):
        for method in methods:
            rendered = _rewritten(method, restriction, flavour, known)
            written = ast.unparse(rendered)
            if written in seen:
                continue
            seen.add(written)
            # a rung open to any chain would make every later one unreachable, so it goes to the end
            narrowed = restriction is not None or _narrows_itself(method)
            (found if narrowed else open_to_any).setdefault(method.name, []).append(rendered)
            if narrowed and holders > widest.get(method.name, (0, method))[0]:
                widest[method.name] = (holders, method)

    # a value the umbrella claims keeps the whole builder, so its rung comes after the named ones.
    # Not written where an open rung follows, which already covers every chain
    for name, (_holders, method) in widest.items():
        if name not in open_to_any:
            found[name].append(_rewritten(method, f"{flavour}[_CapableT]", flavour, known, umbrella=True))
    for name, rungs in open_to_any.items():
        found.setdefault(name, []).extend(rungs)
    return found


def _body(known: dict[str, ast.ClassDef], flavour: str) -> str:
    lines: list[str] = []
    for rungs in _rungs(known, flavour).values():
        lines.append("")
        for rendered in rungs:
            if len(rungs) > 1 and not any(ast.unparse(one) == "overload" for one in rendered.decorator_list):
                rendered.decorator_list.insert(0, ast.Name(id="overload"))
            lines.append("\n".join(f"        {line}" for line in ast.unparse(rendered).splitlines()))
    return "\n".join(lines)


def _abc_import() -> str:
    """The line the mirrored module imports its `collections.abc` names with, copied rather than repeated."""
    line = next(
        one
        for one in VIEWS.read_text(encoding="utf-8").splitlines()
        if one.strip().startswith("from collections.abc import")
    )
    return line.replace("import ", "import Generator, ", 1) if "Generator" not in line else line


def generate() -> str:
    known = _classes(ast.parse(VIEWS.read_text(encoding="utf-8")))
    return _HEADER.format(
        imports=_IMPORTS.format(abc=_abc_import()),
        sync=_body(known, "_SyncPoll"),
        asynchronous=_body(known, "_AsyncPoll"),
    )


def generate_verdict() -> str:
    known = _classes(ast.parse(VIEWS.read_text(encoding="utf-8")))
    matchers = "    from ..matchers import Matcher"
    imports = _IMPORTS.format(abc=_abc_import()).replace(
        matchers, matchers + "\n    from ..outcome import AssertionOutcome"
    )
    return _VERDICT_HEADER.format(imports=imports, body=_body(known, _VERDICT))


_VERDICT_HEADER = '''"""The verdict twin of a value the builder holds.

Generated by `scripts/generate_poll_protocols.py`; do not edit.  `check()` on a typed view hands back
that view's own twin.  This is the one a value reaches through the builder, which is where an element
pivot and the capability umbrella both land.

Flat and self-dispatched for the same measured reason the polling twins are: overloading `check()` on
the builder's own type variable put an `AssertionBuilder[Any]` on the first rung, and every chain built
from a payload typed `dict[str, Any]` then read as a string.  A rung per assertion inverts that.

A name nobody declares stays open, because `__getattr__` answers it: a dynamic assertion is resolved
from the value's own attributes and reaches this proxy too.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
{imports}

    class _CheckAnyValue(Protocol[_P_co]):
        """The verdict surface of a value reached through the builder rather than through a view."""

        @property
        def not_(self) -> _CheckAnyValue[_P_co]: ...
        def __getattr__(self, name: str) -> Callable[..., AssertionOutcome]: ...
{body}
'''


if __name__ == "__main__":
    TARGET.write_text(generate(), encoding="utf-8", newline="")
    TARGET_VERDICT.write_text(generate_verdict(), encoding="utf-8", newline="")
    for written in (TARGET, TARGET_VERDICT):
        subprocess.run(["uv", "run", "ruff", "format", str(written)], cwd=ROOT, check=False, capture_output=True)
        fix = ["uv", "run", "ruff", "check", "--fix", str(written)]
        subprocess.run(fix, cwd=ROOT, check=False, capture_output=True)
        print(f"wrote {written.relative_to(ROOT)}")
